### ISSUE TITLE
stable hlo slice

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-mlir#1003]
Lower stable hlo slice to ttnn. Add unit tests to tt-torch and tt-xla.

**Comment by LPanosTT** [comment]
Op Is added stablehlo --> TTIR,

- Need to add unit test to tt-torch
- Need to add unit test to tt-xla

**Comment by LPanosTT** [comment]
PR for tt-torch tests: https://github.com/tenstorrent/tt-torch/pull/4
PR fot tt-xla tests: https://github.com/tenstorrent/tt-xla/pull/45

**Comment by LPanosTT** [comment]
Tests have been merged
