### ISSUE TITLE
Add StableHLO to TTIR conversion for dynamic_iota OP

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#1011]
Add support for StableHLO to TTIR conversion for `dynamic_iota` OP, lower to ttnn and add unit tests to tt-torch and tt-xla.

Same as `iota` op (#1010), but the result shape is specified dynamically. This op can be converted with the same pattern as `iota` since the result shape can be inferred from the result tensor type, no need to read the input tensor values.

**Comment by mrakitaTT** [comment]
We can support `iota` op and then use `-stablehlo-canonicalize-dynamism` pass to convert `dynamic_iota` to `iota`: _"Replaces dynamic StableHLO ops like DynamicReshapeOp with the corresponding static counterparts"_

**Comment by LPanosTT** [comment]
Bringup merged: [Bringup Arange #1332](https://github.com/tenstorrent/tt-mlir/pull/1332)
