### ISSUE TITLE
Add StableHLO to TTIR conversion for logistic OP

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#1026]
Add support for StableHLO to TTIR conversion for `logistic` OP, lower to ttnn and add unit tests to tt-torch and tt-xla.

Can be lowered to `ttnn.sigmoid`.

**Comment by kmitrovicTT** [comment]
Duplicate of https://github.com/tenstorrent/tt-mlir/issues/970
