### ISSUE TITLE
Add unit tests for StableHLO negate OP to tt-torch and tt-xla

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#1030]

**Comment by mmanzoorTT** [comment]
PR for tt-mlir implementation https://github.com/tenstorrent/tt-mlir/pull/675
PR for tt-xla tests: https://github.com/tenstorrent/tt-xla/pull/15/files

**Comment by mmanzoorTT** [comment]
tt-torch unit tests pending

**Comment by mmanzoorTT** [comment]
tt-torch unit test added https://github.com/tenstorrent/tt-torch/pull/8
