### ISSUE TITLE
ttrt testing

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#104]
Since ttrt is going to be a core development tool, let's brainstorm ways we can test it APIs so eventually we can put it in CI.

These should be push commit level tests, so quick checks to make sure things aren't broken.  Ideally we can run these tests on non-silicon machines

**Comment by tapspatel** [comment]
Blocked by: https://github.com/tenstorrent/tt-mlir/issues/217

**Comment by tapspatel** [comment]
blocked by: https://github.com/tenstorrent/tt-mlir/issues/286

**Comment by tapspatel** [comment]
Tons of silicon + ttrt api testing has gone into tip. Closing issue.
