### ISSUE TITLE
Add StableHLO to TTIR conversion for remainder OP

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#1041]
Add support for StableHLO to TTIR conversion for `remainder` OP, lower to ttnn and add unit tests to tt-torch and tt-xla.

Can be lowered to `ttnn.remainder`.

**Comment by kmitrovicTT** [comment]
Op itself and conversion added in [tt-mlir PR](https://github.com/tenstorrent/tt-mlir/pull/1126), jax tests added in [tt-xla PR](https://github.com/tenstorrent/tt-xla/issues/58) and torch tests added in [tt-torch PR](https://github.com/tenstorrent/tt-torch/issues/32). Closing this issue.
