### ISSUE TITLE
Add Address Alignment Constraints to ChipDesc

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#105]
Let's capture the following address alignment requirements in the chip desc:

```cpp
#define NOC_L1_READ_ALIGNMENT_BYTES       16
#define NOC_L1_WRITE_ALIGNMENT_BYTES      16
#define NOC_PCIE_READ_ALIGNMENT_BYTES     32
#define NOC_PCIE_WRITE_ALIGNMENT_BYTES    16
#define NOC_DRAM_READ_ALIGNMENT_BYTES     32
#define NOC_DRAM_WRITE_ALIGNMENT_BYTES    16
``` 

I think we can summarize these as just:
- `nocL1AddressAlignBytes` 16
- `pcieAddressAlignBytes` 32
- `nocDRAMAddressAlignBytes` 32

I know that pcie and DRAM seem to have different requirements for read vs write, but I think it's sufficient to take the max, plus the only one I truly care about is noc L1.

We want to add these fields to `ChipDesc` in to both the compiler attribute defined in `TTOpsTypes.td` and flatbuffer `types.fbs`. 

We also want to update device runtime API `getCurrentSystemDesc` to scrape these defines from metal.

**Comment by tapspatel** [comment]
I'll include a default compiler pass in this issue: https://github.com/tenstorrent/tt-mlir/issues/132 that will set all default values for each Flatbuffer here. For now, I've updated the test args to include the relevant attributes.

**Comment by tapspatel** [comment]
PR: https://github.com/tenstorrent/tt-mlir/pull/159
