### ISSUE TITLE
[Ops] Support for clip op (ttnn.clip)

### ISSUE THREAD

**Issue by meenakshiramanathan1** [tenstorrent/tt-mlir#1062]

**Comment by mmanzoorTT** [comment]
Adding ttnn.clip and ttnn.clamp is in progress. This [PR](https://github.com/tenstorrent/tt-mlir/pull/1093) provides an initial end-to-end implementation along with stableHLO to TTIR conversion.

**Comment by mmanzoorTT** [comment]
PR #1093 is ready for review

**Comment by mmanzoorTT** [comment]
`ttnn.clip` and `ttnn.clamp` are identical ops; so it is decided to only keep `ttnn.clamp` (https://github.com/tenstorrent/tt-mlir/pull/1093#issuecomment-2456945347). Is `ttnn.clamp` enough for TT-Forge or `ttnn.clip` is also required?

**Comment by nvukobratTT** [comment]
> [@nvukobratTT](https://github.com/nvukobratTT) [@meenakshiramanathan1](https://github.com/meenakshiramanathan1) `ttnn.clip` and `ttnn.clamp` are identical ops; so it is decided to only keep `ttnn.clamp` ([#1093 (comment)](https://github.com/tenstorrent/tt-mlir/pull/1093#issuecomment-2456945347)). Is `ttnn.clamp` enough for TT-Forge or `ttnn.clip` is also required?

We can use clamp as well :)) Once supported, please close this issue so we can map new op on Forge-FE as well :))

**Comment by sdjordjevicTT** [comment]
This one is merged into the main.

**Comment by nvukobratTT** [comment]
@meenakshiramanathan1 let's map this op from Forge as well, and test out currently blocked models from the list above :))
