### ISSUE TITLE
[Ops] Support for tanh op (ttnn.tanh)

### ISSUE THREAD

**Issue by meenakshiramanathan1** [tenstorrent/tt-mlir#1063]

**Comment by uazizTT** [comment]
> [@uazizTT](https://github.com/uazizTT) is this issue wip? :))

I have a PR for it, would appreciate if you can approve so it can be merged :)
sudo chown -R $USER /opt/ttmlir-toolchain](https://github.com/tenstorrent/tt-mlir/pull/1122)

**Comment by nvukobratTT** [comment]
> > [@uazizTT](https://github.com/uazizTT) is this issue wip? :))
> 
> I have a PR for it, would appreciate if you can approve so it can be merged :) ([#1122](https://github.com/tenstorrent/tt-mlir/pull/1122))

Unfortunately, I'm not one of the core owners on the TTIR side. Therefore, my approval wouldn't help. 

Can you please ping the required reviewers once again on the PR as reminder?

**Comment by nvukobratTT** [comment]
@uazizTT any update on this one? :)) Is there a blocker which prevents us from merging tanh changes?
