### ISSUE TITLE
TTNN pow op is missing support for tensor exponent

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#1094]
Metal issue: https://github.com/tenstorrent/tt-metal/issues/13857

This is blocking us from implementing StableHLO to TTIR conversion for power OP https://github.com/tenstorrent/tt-mlir/issues/1033 That op is used in LLAMA model and we have no easy workaround.

**Comment by mrakitaTT** [comment]
FYI @tt-mpantic

**Comment by staylorTT** [comment]
Who can we assign to this issue?

**Comment by kmitrovicTT** [comment]
Closing as it is excessive. Issues that referenced this one will reference metal issue directly.
