### ISSUE TITLE
Add golden mode in flatbuffer through python TTIR lowering infra

### ISSUE THREAD

**Issue by tapspatel** [tenstorrent/tt-mlir#1108]
Add respective runtime components to fallback to host and do golden comparison

**Comment by tapspatel** [comment]
```LogicalResult translateTTNNToFlatbuffer(Operation *op, llvm::raw_ostream &os, llvm::DenseMap<std::string, std::string>& goldenMap) {
```

cannot append additional struct to this because function declaration only defines Operation and raw_ostream support

see: https://mlir.llvm.org/doxygen/namespacemlir.html#a86f6096a57734eed0290d2ab34ad5e79 
TranslateFromMLIRFunction

**Comment by tt-mpantic** [comment]
@tapspatel any updates on this one ? 
This one is marked as P0, and we need to report weekly updates on P0 bugs...

**Comment by tapspatel** [comment]
I've finished getting flatbuffer support and storing golden data into the flatbuffer itself. I'm working on runtime changes to do the golden comparison now.
