### ISSUE TITLE
[TTNN] Create a higher level toLayout op in TTNN

### ISSUE THREAD

**Issue by sdjordjevicTT** [tenstorrent/tt-mlir#1137]
Introduce a higher level toLayout op that will encapsulate the TTNN layout attribute target state.

This issue is part of the TTNN backend pipeline refactor. This doc captures the TTNN backend pipeline refactor:
[TTNN Defaults - Design Doc](https://docs.google.com/document/d/1As-1mRKQlFig9tJjdhGUlMOHp4cIaWPvpjR-L61xEuM/edit?tab=t.0)

**Comment by svuckovicTT** [comment]
Is there anything else to do besides what @jnie-TT did in #840 and #1105?

**Comment by sdjordjevicTT** [comment]
Same as I said in #1138:
The main purpose of this issue is to capture the intent outlined in the design doc. We’ll likely close it, but let’s wait until someone is assigned and has taken a closer look.
