### ISSUE TITLE
Build fails with new version of tt-metal

### ISSUE THREAD

**Issue by vmilosevic** [tenstorrent/tt-mlir#1146]
We have build errors with new version of tt-metal
https://github.com/tenstorrent/tt-mlir/actions/runs/11660244306/job/32462210096

```
/__w/tt-mlir/tt-mlir/third_party/tt-metal/src/tt-metal/tt_metal/hw/inc/dev_msgs.h:208:26: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
  208 |     volatile uint8_t pad[8 - DebugNumUniqueRiscs];
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
/__w/tt-mlir/tt-mlir/third_party/tt-metal/src/tt-metal/tt_metal/hw/inc/dev_msgs.h:222:27: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
  222 |     volatile uint16_t pad[16 - DebugNumUniqueRiscs * 2];
```

**Comment by nsmithtt** [comment]
There is another build failure because of UMD: https://github.com/tenstorrent/tt-umd/issues/251

**Comment by kmabeeTT** [comment]
Just heads up, manual tt-metal uplift was started last week, and hit other issues, some solved (tt-metal fixes, tt-mlir changes), some not fully solved (tt-metal fix)

https://github.com/tenstorrent/tt-mlir/pull/1119

**Comment by kmabeeTT** [comment]
Opened PR for demoting this error to warning, tested locally, needed to update 3 headers.

https://github.com/tenstorrent/tt-mlir/pull/1254

If we merge this next auto-uplift tt-metal stands a chance.  Confirmed UMD fix made it's way there.
