### ISSUE TITLE
RuntimeError: Embedding Device Operation Layout Mismatch - Expected ROW_MAJOR

### ISSUE THREAD

**Issue by kamalrajkannan78** [tenstorrent/tt-mlir#1181]
## Observed Behaviour

```
>       all_outputs = run_binary(self.compiled_binary, int(ProgramId.FORWARD), inputs_and_parameters)
E       RuntimeError: TT_FATAL @ /proj_sw/user_dev/kkannan/nov6_forge/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/embedding/device/embedding_device_operation.cpp:25: a.get_layout() == Layout::ROW_MAJOR
E       info:
E       Error
```

## logs 

[phi3_issue.log](https://github.com/user-attachments/files/17652651/nov6_phi3_cls.log)

**Comment by nvukobratTT** [comment]
Is this issue duplicate of this one:
- https://github.com/tenstorrent/tt-mlir/issues/1215

**Comment by kamalrajkannan78** [comment]
> Is this issue a duplicate of this one>
> 
> * [Embedding input in TILE layout, despite ttnn.embedding doesn't support it #1215](https://github.com/tenstorrent/tt-mlir/issues/1215)

yes Nikola. As discussion is going on [there](https://github.com/tenstorrent/tt-mlir/issues/1215) , I close this MR.
