### ISSUE TITLE
internal-build.md docker build syntax error

### ISSUE THREAD

**Issue by johnwalicki** [tenstorrent/tt-mlir#1191]
The [Internal Build Notes / IRD](https://docs.tenstorrent.com/tt-mlir/internal-build.html#internal-build-notes--ird) documentation at [https://github.com/tenstorrent/tt-mlir/blob/main/docs/src/internal-build.md](https://github.com/tenstorrent/tt-mlir/blob/main/docs/src/internal-build.md) has a `docker build` syntax error.  The `-build-args` flag should be `--build-arg`

I also noticed several spelling/grammar/markdown lint errors.

For your consideration, I will submit a PR to fix these minor issues.

**Comment by staylorTT** [comment]
Thank you for the feedback. We definitely welcome and will review any PR.
