### ISSUE TITLE
Data Type Mismatch: Expected BFLOAT16 for input_tensor_a in tilize_with_val_padding_op

### ISSUE THREAD

**Issue by kamalrajkannan78** [tenstorrent/tt-mlir#1193]
## Description

-  Nbeats model faces Data Type Mismatch at runtime 

## Reproduce

```
git checkout kkannan/forge_model_issues_nov12
git submodule update --recursive
pytest forge/test/model_demos/high_prio/cnn/pytorch/test_nbeats.py -svv
```

## observed behaviour

```
RuntimeError: TT_FATAL @ /proj_sw/user_dev/kkannan/nov6_forge/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/data_movement/tilize_with_val_padding/device/tilize_with_val_padding_op.cpp:19: input_tensor_a.get_dtype() == DataType::BFLOAT16
```

## logs

- [Nbeats_issue.log.zip](https://github.com/user-attachments/files/17716178/Nbeats_issue.log.zip)

**Comment by sdjordjevicTT** [comment]
Can you please provide more details on how to repro this?

**Comment by kamalrajkannan78** [comment]
I added repro steps now!

**Comment by nvukobratTT** [comment]
@kamalrajkannan78 can you add TTIR for this issue as well? That way, it's much easier for MLIR folks to reproduce these issues without the need of running Forge-Fe as well :))

**Comment by kamalrajkannan78** [comment]
on latest main , Nbeats not faces this issue . ref - https://github.com/tenstorrent/tt-forge-fe/pull/751
