### ISSUE TITLE
Build tt-mlir failed

### ISSUE THREAD

**Issue by ggzhang213** [tenstorrent/tt-mlir#1263]
I build tt-mlir with 
`cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17 -DTTMLIR_ENABLE_RUNTIME=ON`
`cmake --build build`

![Image](https://github.com/user-attachments/assets/841904ff-e87f-440f-904d-a6781afe0af4)
The error shown in the image occurred. How can I resolve this issue?

**Comment by nsmithtt** [comment]
Hi @ggzhang213, this usually means that git lfs failed.  Do you have git lfs installed?  Also what system are you building on?

**Comment by staylorTT** [comment]
Hi @ggzhang213 Just checking in to see if you were able to figure this our or still needed help?

**Comment by staylorTT** [comment]
hi @ggzhang213, checking in here to see if you had any additional questions or help required from us?

**Comment by staylorTT** [comment]
I am marking this fixed for now, if you have any additional feedback or issues please re-open.
