### ISSUE TITLE
[Ops] Support for remainder op (ttnn.remainder)

### ISSUE THREAD

**Issue by kamalrajkannan78** [tenstorrent/tt-mlir#1268]
Note : Remainder op already supported in [ttnn](https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api/ttnn.remainder.html#ttnn.remainder)

**Comment by sdjordjevicTT** [comment]
The reminder op is implemented:
https://github.com/tenstorrent/tt-mlir/blob/16edb11e488f1dcbe1e1202ec926c3ab318f5438/include/ttmlir/Dialect/TTIR/IR/TTIROps.td#L493C1-L493C63
