### ISSUE TITLE
Get dedicate runners from cloud to support / speedup our development

### ISSUE THREAD

**Issue by staylorTT** [tenstorrent/tt-mlir#128]

**Comment by staylorTT** [comment]
@tapspatel and I met with cloud and for now we were told to work with the overall GitHub CI effort and to use the cloud portal to test out what we want. Going to chat with metal to see how they setup their GH runners.

**Comment by tapspatel** [comment]
acquired the following

<img width="126" alt="image" src="https://github.com/user-attachments/assets/6353a924-9d8e-475d-9ae0-b5dbfaa2530b">
