### ISSUE TITLE
ttir.broadcast op failure due to attempting to modify a replaced/erased op

### ISSUE THREAD

**Issue by mmanzoorTT** [tenstorrent/tt-mlir#1348]
This failure is happening due to folding of `ttir.broadcast` op. If an op consume one `broadcast` op then folding doesn't cause any issue. However, if multiple operands are broadcasted then `broadcast` folding causes crash due to lazy update approach. PR #1252 resolves the broadcast folding issue in case of redundant/empty broadcast. We have multiple use cases for PyTorch models where folding will generate incorrect results. Few of the stablehlo graphs are following. I don't know if tt-metal can handle such cases; otherwise, we need a dedicated `ttnn.broadcast` op for these graphs.

Example 1:
```
module {
  func.func @main(%arg0: tensor<1x23x40x1xf32>, %arg1: tensor<128xf32>) -> tensor<1x23x40x128xf32> {
    %0 = stablehlo.broadcast_in_dim %arg0, dims = [0, 1, 2, 3] : (tensor<1x23x40x1xf32>) -> tensor<1x23x40x128xf32>
    %1 = stablehlo.broadcast_in_dim %arg1, dims = [3] : (tensor<128xf32>) -> tensor<1x23x40x128xf32>
    %2 = stablehlo.divide %0, %1 : tensor<1x23x40x128xf32>
    return %2 : tensor<1x23x40x128xf32>
  }
}
```
Example 2:
```
module {
  func.func @main(%arg0: tensor<32xi64>, %arg1: tensor<32x1xi64>) -> tensor<32x32xi1> {
    %0 = stablehlo.broadcast_in_dim %arg0, dims = [1] : (tensor<32xi64>) -> tensor<32x32xi64>
    %1 = stablehlo.broadcast_in_dim %arg1, dims = [0, 1] : (tensor<32x1xi64>) -> tensor<32x32xi64>
    %2 = stablehlo.compare  GT, %0, %1,  SIGNED : (tensor<32x32xi64>, tensor<32x32xi64>) -> tensor<32x32xi1>
    return %2 : tensor<32x32xi1>
  }
}
```
Example 3:
```
module {
  func.func @main(%arg0: tensor<16x1xf32>, %arg1: tensor<1x1x32xi64>) -> tensor<1x16x32xf32> {
    %0 = stablehlo.convert %arg1 : (tensor<1x1x32xi64>) -> tensor<1x1x32xf32>
    %1 = stablehlo.broadcast_in_dim %arg0, dims = [1, 2] : (tensor<16x1xf32>) -> tensor<1x16x32xf32>
    %2 = stablehlo.broadcast_in_dim %0, dims = [0, 1, 2] : (tensor<1x1x32xf32>) -> tensor<1x16x32xf32>
    %3 = stablehlo.multiply %1, %2 : tensor<1x16x32xf32>
    return %3 : tensor<1x16x32xf32>
  }
}
```
Example 4:
```
module {
  func.func @main(%arg0: tensor<1x10xi64>, %arg1: tensor<10x1xi64>) -> tensor<10x10xi64> {
    %0 = stablehlo.broadcast_in_dim %arg0, dims = [0, 1] : (tensor<1x10xi64>) -> tensor<10x10xi64>
    %1 = stablehlo.broadcast_in_dim %arg1, dims = [0, 1] : (tensor<10x1xi64>) -> tensor<10x10xi64>
    %2 = stablehlo.subtract %0, %1 : tensor<10x10xi64>
    return %2 : tensor<10x10xi64>
  }
}
```

Error message
```
ttmlir-opt:   compiler/tt-mlir/env/build/llvm-project-prefix/src/llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:1589:   virtual void   mlir::ConversionPatternRewriter::startOpModification(mlir::Operation *):   Assertion `!impl->wasOpReplaced(op) && "attempting to modify   a replaced/erased op"' failed.
```

**Comment by mmanzoorTT** [comment]
FYI @uazizTT @AleksKnezevic @mrakitaTT

**Comment by uazizTT** [comment]
Thanks @mmanzoorTT can you point out the case of incorrect results even after using PR #1252 ?

I am working to move broadcastOp folding to separate pass but I doubt if that will solve the issue that is not fixed after PR #1252.

**Comment by mmanzoorTT** [comment]
Can tt-metal handle such cases where both operands are required to be broadcasted based on the output shape? If not then we need a dedicated `ttnn.broadcast` op and all of these foldings/fixes can go away.

**Comment by uazizTT** [comment]
Yeah that's going to be tricky, I think it can be a candidate of workarounds in TTIR where we can add additional dummy instruction to take the second (or third) broadcast until the support is added in ttnn.
