### ISSUE TITLE
Unsupported data format during lowering from TTForge to TTIR: Bfp2_b

### ISSUE THREAD

**Issue by kamalrajkannan78** [tenstorrent/tt-mlir#1374]
## Description

-  Unsupported data format during lowering from TTForge to TTIR: Bfp2_b. unsupported data fromat assertion from lower_to_mlir.cpp
`RuntimeError: TT_ASSERT @ /proj_sw/user_dev/mramanathan/bgdlab14_forge/tt-forge-fe/forge/csrc/passes/lower_to_mlir.cpp:503: false`

## Reproduce

```
git checkout mramanathan/llama3_mlir_repro
git submodule update --recursive
cmake --build build -- install_ttforge
pytest forge/test/model_demos/high_prio/nlp/pytorch/test_llama3 -k "test_llama3_causal_lm"
```

## Observed Behaviour
>  Unsupported data format during lowering from TTForge to TTIR: Bfp2_b

## Logs

- [llama3.log](https://github.com/user-attachments/files/17872398/llama3.log)

- TTIR graphs are present in logs

**Comment by meenakshiramanathan1** [comment]
```
E           OSError: You are trying to access a gated repo.
E           Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B.
E           401 Client Error. (Request ID: Root=1-672c7a41-014fc0106338524b4cce14d6;cb7fab69-5ad8-4cbc-ac6d-a02791135219)
E           
E           Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B/resolve/main/config.json.
E           Access to model meta-llama/Meta-Llama-3-8B is restricted. You must have access to it and be authenticated to access it. Please log in.
``` 

- if you face above issue,  use your token in place of 

```
from huggingface_hub import login
login(token="")
```

**Comment by kamalrajkannan78** [comment]
solved by https://github.com/tenstorrent/tt-forge-fe/pull/802
