### ISSUE TITLE
TTRT - Golden Artifacts

### ISSUE THREAD

**Issue by vprajapati-tt** [tenstorrent/tt-mlir#1507]
- After running ttrt with the `--golden` option doesn't actually yield any specific artifacts beyond printing to `stdout`. It would be useful for end users (and also `explorer`) to store these results. 
- Currently #1234 is blocked on this support being included.

**Comment by tapspatel** [comment]
Features to add:
- store golden tensors to artifacts as torch tensors with name=loc
- store intermediate tensors to artifacts as torch tensors with name=loc
- track test pass/failure and raise an exception on mismatched pcc
- print golden pcc dictionary of all intermediate/output tensor comparisons and their golden results (pcc, atol, rtol, abs, etc)
