### ISSUE TITLE
Uplift llvm it tt-mlir to match XLA

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-mlir#188]
Right now, XLA and tt-mlir use different commits. Please update tt-mlir to use git tag 694b132177a96a61dac62b3e3d2989a063feafa7

A blind update fails compile with build warnings, which if ignored fails on some tests.

**Comment by mmanzoorTT** [comment]
tt-mlir is updated to use `9ddfe62f5c11e3f65f444209f514029ded2d58b9` commit for `llvm` matching latest requirements for `XLA` in PR #215. This PR also modifies the deprecated calls.
