### ISSUE TITLE
Adopt new device runtime

### ISSUE THREAD

**Issue by staylorTT** [tenstorrent/tt-mlir#19]

**Comment by pilkicTT** [comment]
Update: in progress - have a working version, but still needs to be cleaned up. PR(s) should follow soon.

**Comment by pilkicTT** [comment]
Once this [PR](https://github.com/tenstorrent/tt-forge/pull/8) is complete we can close this issue.

**Comment by pilkicTT** [comment]
Closing the issue, PR has been completed.
