### ISSUE TITLE
Build break missing `_ttnn.so`

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#197]
https://github.com/tenstorrent/tt-mlir/actions/runs/9996298139/job/27630356449#step:8:7

**Comment by jnie-TT** [comment]
Was able to reproduce on a fresh clone... TTNN_LIBRARY is set correctly but doesn't exist when the check happens because it hasn't been built yet - need to somehow signal cmake that TTNN_LIBRARY depends on tt-metal to be built first.
