### ISSUE TITLE
Add CI runners

### ISSUE THREAD

**Issue by tapspatel** [tenstorrent/tt-mlir#217]
As discussed offline. We have 5 n150s + 3 n300s. Not posting their IP information here due to its sensitivity.

**Comment by vmilosevic** [comment]
Runners are added, and drivers and tools are installed in a manner similar to the setup done for tt-metal runners.

<img width="645" alt="image" src="https://github.com/user-attachments/assets/5739e8a8-bcfc-473d-a404-e14c81ff76cc">

Runners can pick up jobs marked with corresponding tags

https://github.com/tenstorrent/tt-mlir/actions/runs/10148955565/job/28089853623
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/4d747161-9f48-4b2d-8d89-e3bcb16ce524">
