### ISSUE TITLE
[Ops] Add TTIR const op

### ISSUE THREAD

**Issue by rpavlovicTT** [tenstorrent/tt-mlir#231]
It'd be good to have an op in tt-mlir that creates tensor filled by a certain value. This is supported in ttnn by [ttnn::full](https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/ttnn/full.html) that accepts `fillValue` as an arg.

Proposal is to have TTIR const op, analogous to [tosa::const](https://mlir.llvm.org/docs/Dialects/TOSA/#tosaconst-mlirtosaconstop). TTIR const op lowers to TTNN full op.

When TTIR const op is added, support lowering tosa::const->ttir::const.

**Comment by mrakitaTT** [comment]
We've encountered need for this in StableHLO conversion too, there is a discussion here: #507

**Comment by nsmithtt** [comment]
Closing as dup of #507 since more discussion has happened over there.

**Comment by mrakitaTT** [comment]
@nsmithtt I've been asked by MLIR Dialect folks to open separate issues for ops support in TTIR and for ops conversion, for better awareness and effort tracking between teams, so I will reopen this issue and assign it to myself and do it together with #507

**Comment by nsmithtt** [comment]
Sounds good
