### ISSUE TITLE
Human in loop cycle, rerun compilation

### ISSUE THREAD

**Issue by staylorTT** [tenstorrent/tt-mlir#25]
Overrides are going to be crucial with the visualizer tool or for any developer to further fine-tune their compilation results on the MLIR platform. We need to create some method with which these overrides can be accessed easily by end users (and the visualizer).

**To Do**:
- Implement an Override Pass that parses some JSON to change the attributes of a ttmlir module.
- Link this override pass to Python bindings to make it user accessible.

**Key Questions**:
- Find the format in which the JSON serializes the update. How would it recognize the ID of the Op in python vs C++?
- What would this pass return? A new module or a serialized result using opt?

> Vraj

**Comment by staylorTT** [comment]
This will carry over into Milestone 1. Setting it over now. There is a risk that the UI never gets opensourced so we need to figure out the path forward for visualizer.

**Comment by odjuricicTT** [comment]
This functionality exists now within Forge UI. 

Currently we support overriding anything related to the tensor / tensor layout. Future work will entail adding op specific overrides for each op.
