### ISSUE TITLE
Add ttir broadcast op

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#251]
We should add support for an explicit broadcast op in ttir.

**Comment by rpavlovicTT** [comment]
@nsmithtt @sdjordjevicTT 

Hey folks, I just wanted to clarify what we want to do about broadcasting. 

Other dialects like ONNX, Tosa support implicit operand broadcasting. For reference [ONNX mlir broadcasting](https://github.com/onnx/onnx/blob/main/docs/Broadcasting.md). For example in Tosa, these are valid ops:

```  
%0 = tosa.add %arg0, %arg1 : (tensor<2x1xf32>, tensor<1xf32>) -> tensor<2x1xf32>
return %0 : tensor<2x1xf32>

---

%0 = tosa.add %arg0, %arg1 : (tensor<17x16x15x14xf32>, tensor<15x1xf32>) -> tensor<17x16x15x14xf32>
return %0 : tensor<17x16x15x14xf32>

```

I talked to @sdjordjevicTT about cases where he hit asserts in our current compiler about eltwise ops having unequally shaped operands. To overcome this I see 2 options in tt-mlir:

1. Implement explicit broadcast op in TTIR. 
    a. add a pass in TTIR that inserts broadcasts where needed and adjusts tensor shapes, or
    b. tt-forge creates broadcast nodes and emits those ops as all other ops in TTIR, leaving current eltwise constraints in TTIR intact.
2. Implement an interface for tensor shape inference, where for each tensor, its shape would be inferred and potentially reshaped if needed. We could forbid/permit this for certain op classes. 

On a side note, IIUC, our `toLayoutOp` needs to know shape of each tensor it is applied to, so it can build MemRef. Am I right @nsmithtt ? So whatever option we choose from above, it should be done before `ttir-layout` pass?

**Comment by nsmithtt** [comment]
@rpavlovicTT, what do you think is the most robust approach here?  I think implicit broadcasting could be a nice mechanism to have at TTIR dialect, and leave it up to the target backend to determine how to implement that.  This has a nice property of TTNN just being passthrough, since it supports implicit broadcast.  Metal backend can always run a pass (agreed, before toLayout) that turns the implicit into explicit.

**Comment by rpavlovicTT** [comment]
I lean toward the implicit broadcasting too. Then we'd have to replace current eltwise trait with custom verifiers as you noted, and that looks good to me. 

I am not sure how implicit broadcast would work wrt. tensor layout and memory configs. Given above example:
```
%0 = tosa.add %arg0, %arg1 : (tensor<17x16x15x14xf32>, tensor<15x1xf32>) -> tensor<17x16x15x14xf32>
```
do we pretend that tensor %arg1 is of dims 15x1xf32 and lay it out like that and let TTNN take care of broadcasting data, or should we actually worry about real dims in the compiler?

**Comment by nsmithtt** [comment]
> do we pretend that tensor %arg1 is of dims 15x1xf32 and lay it out like that and let TTNN take care of broadcasting data, or should we actually worry about real dims in the compiler?

Yeah it's definitely a bit tricky to express for tensor layout, I think by default we should have ttir construct it like this:
```
#layout = #tt.layout<(d0, d1) -> (d0, d1), undef, <1x1>, memref<15x1xf32, #tt.memory_space<l1>>>
tensor<15x1xf32, #layout>
``` 

We need to work out details for how this gets expressed for multi-core and/or tilized, but I'm not too worried about it because so far the TTNN runtime doesn't actually look at anything from the layout desc.  We'll only have to model this properly when we get to modeling L1 footprint.

For metal backend we want to transform the broadcasted tensor to be purely expressed as an iteration space, it'd look like this:
```
#layout = #tt.layout<(d0, d1, d2, d3) -> (d2, 0), undef, <1x1>, memref<15x1xf32, #tt.memory_space<l1>>>
tensor<17x16x15x14xf32, #layout>
```
Note that the tensor shape changes, becomes post-broadcasted, but the affine map itself implements the broadcast by dropping all of the broadcasted dims and replacing them with 0's.  It's a bit more explicit in this way.
