### ISSUE TITLE
Streamline TTRT API calls for Upstream python tools

### ISSUE THREAD

**Issue by vprajapati-tt** [tenstorrent/tt-mlir#252]
**Planned Deltas**
- Output from API to strings (ex: io.StringIO) instead of dumping to terminal, specifically for `perf` results
- Wrap arguments for API calls like `read`, `query`, etc... to use JSON/Python Dict objects instead of `argparse.parser` results.

**Comment by tapspatel** [comment]
merged: a288b1330787d68cd59507a33aec8d195b53086a
