### ISSUE TITLE
Investigate how graphs are emitted through pjrt device

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-mlir#262]
Can you please take a look at how jax workflows are emitted through the PJRT device. Please investigate two use cases:

- Training
  - How do forward/backward/optimizer graphs get emitted? 
  - Are they separate? If so, how can we link the params from the forward/backward graphs?

- Multidevice
  - What do multi-device graphs look like?

**Comment by mmanzoorTT** [comment]
It is required to registered custom plugin to execute the code on a hardware/accelerator (e.g. `tt wormwhole`). Once the plugin is registered then any JAX code code will be executed on the device with highest priority. CPU/GPU/TPU are registered by default. 

A simple linear regression training example can be found [here](https://colab.research.google.com/drive/12BJU0VZm51OR7S7n_XabYZFyDSSVu8-i#scrollTo=LzYUHdLAPjgS)

**Comment by mmanzoorTT** [comment]
### MNIST training example
[This script](https://colab.research.google.com/drive/1Z5hvBriOP6g83nIHW5XdSkSCgM6T68I8?usp=sharing
) creates a simple neural network of 4 layers of [784, 512, 512, 10] and uses relu as activation function. The update function does forward-pass/back-propagation/weight-update tasks.

**Comment by mmanzoorTT** [comment]
JAX jit mostly merge all the functions and create one for users code. jitted graph does have some additional function created internally. output/param form one function can be passed to other functions in python script. 
A jitted function will be executed on AI device if any of the input parameter is stored/located on the said device. If all the inputs are currently stored on CPU then the jitted function will be executed on CPU. function argument `backend` can also be used to instruct where the `jitted` function will be executed (`backed` argument is deprecated and storage location of the input argument is required to determine execution device).

A sample code for simple regression training can be found in [PR](https://github.com/tenstorrent/tt-xla/pull/16) where forward/backward graph is executed on `tt` device and rest of the code is executed on `cpu` backend

**Comment by mmanzoorTT** [comment]
A multi device example for training MNIST model. 

https://colab.research.google.com/drive/1XT7yxG3BvzVldrCIvaFkci59nl0_6QdJ?usp=sharing

**Comment by mmanzoorTT** [comment]
A multi device pipelined training example using JAX/FLAX

https://colab.research.google.com/drive/1NtwmdfzHgAaCbRlK7f2_TYSFPXKapJ4q?usp=sharing

**Comment by mmanzoorTT** [comment]
All these example generate `stableHLO` graphs for reference purpose.
