### ISSUE TITLE
Add physical core coords to system desc

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#264]
We want to use the following metal device APIs to add to system desc:
```c++
CoreCoord logical_grid_size() const;
CoreCoord worker_core_from_logical_core(const CoreCoord &logical_core) const;

CoreCoord dram_grid_size() const;
CoreCoord dram_core_from_logical_core(const CoreCoord &logical_core) const;
```

This should populate a new flatbuffer fields:
```
table CoreMapping {
    logical: Dim2d;
    physical: Dim2d;
};

table SystemDesc {
    ...
   worker_core_mapping: [CoreMapping];
   dram_core_mapping: [CoreMapping];
};
```

Blocked by #132, once 132 is complete it will be much easier to make updates to system desc, because we can remove system desc from all of the tests.

**Comment by kmabeeTT** [comment]
Thanks Nick, I'm going to aim to take a look at this as my first task for this project, shortly.

**Comment by tapspatel** [comment]
PR for removing system desc: https://github.com/tenstorrent/tt-mlir/pull/289

**Comment by tapspatel** [comment]
merged: 5dc6d8263b9a5565b28caac906e447c515006761

**Comment by kmabeeTT** [comment]
Started looking at this yesterday and experimenting, learning the files, by adding a dummy uint32 field into SystemDesc and made sure I could write it to disk and reload it as experiment through various flows, then added function to return all worker, dram, eth logical to physical mappings used by `getCurrentSystemDesc()`, working on getting it passed through the same files after updating .td and .fbs the same way a single field could, then would open PR.

**Comment by kmabeeTT** [comment]
FYI @nsmithtt , I got some initial changes working that match above spec, but after rebasing and looking at things with a fresh set of eyes, I realized that we need an array of arrays, not just an array, since first array is for chips (missing) and 2nd level of array is for the per-core mappings (many).  

Here is alternative/fixed version that I think is the cleanest that I'm currently pursing the changes for (not super straightforward, since we don't have any examples nearby in code for this type of situation with multiple levels of indirection.  The .fbs and .td changes were straightforward, but the rest is WIP..


```
struct CoreMapping {
  logical: Dim2d;
  physical: Dim2d;
}

table ChipCoreMapping {
  worker: [CoreMapping];
  eth: [CoreMapping];
  dram: [CoreMapping];
}

table SystemDesc {
  chip_descs: [ChipDesc];
  chip_desc_indices: [uint32];
  chip_capabilities: [ChipCapability];
  chip_coords: [ChipCoord];
  chip_core_mappings: [ChipCoreMapping];
  chip_channels: [ChipChannel];
}
```

**Comment by nsmithtt** [comment]
@kmabeeTT, this is a great catch and a mistake in my original proposal, I think we should put `ChipCoreMapping` inside of `ChipDesc`, this way we don't need an array of arrays.  I think organizationally this makes sense too, lmk what you think.

Also in reading the actual print out, I wonder if we need logical core coord, perhaps it's more succinct to make this just:
```
table ChipCoreMapping {
  worker: [Dim2d];
  eth: [Dim2d];
  dram: [Dim2d];
}

table ChipDesc {
  ...
  chip_core_mappings: ChipCoreMapping;
}
```

I think this is OK, we can just document that the physical core coords are stored in row major order and we can just reconstruct the logical topology.  I think it's especially true for the ethernet and dram coords, where we want to try different logical topologies, so it doesn't make sense to prescribe one in system desc.

**Comment by kmabeeTT** [comment]
@nsmithtt - Thanks for your reply! No prob, sure can move it to `ChipDesc` like you said, and switch to array of `Dim2d` physical cores. I'm not sure how this mapping intends to be used, but if you think it's fine without prescribed logical coordinates, I will take your word for it!  Let me get my existing changes working after rebase, then will update based on above.

**Comment by kmabeeTT** [comment]
There was some more offline discussion, an array of Dim2D is printed not so nice as ..

```
{worker = 2x1x3x1x4x1x5x1x7x1x8x1x9x1x10x1x2x2x3x2x4x2x5x2x7x2x8x2x9x2x10x2x2x3x3x3x4x3x5x3x7x3x8x3x9x3x10x3x2x4x3x4x4x4x5x4x7x4x8x4x9x4x10x4x2x6x3x6x4x6x5x6x7x6x8x6x9x6x10x6x2x7x3x7x4x7x5x7x7x7x8x7x9x7x10x7x2x8x3x8x4x8x5x8x7x8x8x8x9x8x10x8x2x9x3x9x4x9x5x9x7x9x8x9x9x9x10x9, dram = 11x0x1x0x5
```

so decided to do this:

```
     - Create TT_CoreCoordAttr layer w/ Y,X members to make printing nicer
       and in the format [(1, 2), (2, 3)] for 2 core coordinates.
```
so resulting MLIR for `SystemDesc` for N300 looks like:


```
module attributes {tt.device = #tt.device<#tt.grid<8x8, (d0, d1) -> (0, d0, d1)>, [0]>, tt.system_desc = #tt.system_desc<[{arch = <wormhole_b0>, grid = 7x8, l1_size = 1499136, num_dram_channels = 12, dram_channel_size = 1073741824, noc_l1_address_align_bytes = 16, pcie_address_align_bytes = 32, noc_dram_address_align_bytes = 32, physical_cores = {worker = [(2, 1), (2, 2), (2, 3), (2, 4), (2, 6), (2, 7), (2, 8), (2, 9), (3, 1), (3, 2), (3, 3), (3, 4), (3, 6), (3, 7), (3, 8), (3, 9), (4, 1), (4, 2), (4, 3), (4, 4), (4, 6), (4, 7), (4, 8), (4, 9), (5, 1), (5, 2), (5, 3), (5, 4), (5, 6), (5, 7), (5, 8), (5, 9), (7, 1), (7, 2), (7, 3), (7, 4), (7, 6), (7, 7), (7, 8), (7, 9), (8, 1), (8, 2), (8, 3), (8, 4), (8, 6), (8, 7), (8, 8), (8, 9), (9, 1), (9, 2), (9, 3), (9, 4), (9, 6), (9, 7), (9, 8), (9, 9), (10, 1), (10, 2), (10, 3), (10, 4), (10, 6), (10, 7), (10, 8), (10, 9)], dram = [(11, 0), (1, 0), (5, 0), (7, 0), (1, 5), (11, 5), (2, 5), (9, 5), (8, 5), (3, 5), (5, 5), (7, 5)], eth = [(6, 9), (6, 1)], eth_inactive = [(6, 7), (6, 2), (6, 8), (0, 4), (0, 6), (0, 3), (0, 7), (0, 2), (0, 8), (6, 6), (0, 1), (6, 3), (0, 9)]}}, {arch = <wormhole_b0>, grid = 7x8, l1_size = 1499136, num_dram_channels = 12, dram_channel_size = 1073741824, noc_l1_address_align_bytes = 16, pcie_address_align_bytes = 32, noc_dram_address_align_bytes = 32, physical_cores = {worker = [(2, 1), (2, 2), (2, 3), (2, 4), (2, 6), (2, 7), (2, 8), (2, 9), (3, 1), (3, 2), (3, 3), (3, 4), (3, 6), (3, 7), (3, 8), (3, 9), (4, 1), (4, 2), (4, 3), (4, 4), (4, 6), (4, 7), (4, 8), (4, 9), (5, 1), (5, 2), (5, 3), (5, 4), (5, 6), (5, 7), (5, 8), (5, 9), (7, 1), (7, 2), (7, 3), (7, 4), (7, 6), (7, 7), (7, 8), (7, 9), (8, 1), (8, 2), (8, 3), (8, 4), (8, 6), (8, 7), (8, 8), (8, 9), (9, 1), (9, 2), (9, 3), (9, 4), (9, 6), (9, 7), (9, 8), (9, 9), (10, 1), (10, 2), (10, 3), (10, 4), (10, 6), (10, 7), (10, 8), (10, 9)], dram = [(11, 0), (1, 0), (5, 0), (7, 0), (1, 5), (11, 5), (2, 5), (9, 5), (8, 5), (3, 5), (5, 5), (7, 5)], eth = [(0, 9), (0, 1)], eth_inactive = [(6, 4), (0, 8), (0, 2), (0, 7), (0, 3), (0, 6), (0, 4), (6, 9), (6, 1), (6, 8), (6, 2), (6, 7), (6, 3), (6, 6)]}}], [0, 1], [<pcie|host_mmio>, <pcie>], [<0, 0, 0, 0>]>} {
```

Going to open PR now that changes are cleaned up and passing (with some local hacks for bypassing #380 and #388, other systemdesc issues)
