### ISSUE TITLE
CI silicon runners down + hanging

### ISSUE THREAD

**Issue by tapspatel** [tenstorrent/tt-mlir#286]
n150-1 is offline in CI
CI scripts don't have a reset step (analogous to metal reset step)
Branch: tpatel/issue-104
Pipeline hangs at the post build cache ttmlir-toolchain step:  https://github.com/tenstorrent/tt-mlir/actions/runs/10220175581/job/28279994297
need ability to build artifacts offline and upload into another machine (currently everything is too tightly coupled together)

**Comment by tapspatel** [comment]
Pipeline hangs at the post build cache ttmlir-toolchain step: https://github.com/tenstorrent/tt-mlir/actions/runs/10220175581/job/28279994297

resolved, GitHub runner just takes a long time

**Comment by vmilosevic** [comment]
n150-1 is back online

Added board reset using the same method as on tt-metal - "Set up runner" script added as a hook on runner host.
Scripts and .env are installed using ansible workflow "machines/ci/playbooks/setup/0-install-reset-cleanup.yaml"


![Image](https://github.com/user-attachments/assets/4eb6f341-8052-42af-a2eb-3cd889f2ad80)

**Comment by tapspatel** [comment]
issue resolved, thanks @vmilosevic ! closing
