### ISSUE TITLE
See what it takes to build the PJRT Device

### ISSUE THREAD

**Issue by staylorTT** [tenstorrent/tt-mlir#30]

**Comment by AleksKnezevic** [comment]
Basic pjrt device builds on https://github.com/AleksKnezevic/xla. Linking to ttmlir now.

**Comment by AleksKnezevic** [comment]
We can build a pjrt device using XLA. This requires us to create a bazel build system in ttmlir. 
Maintaining two build is suboptimal, so currently looking at creating a standalone pjrt device.
