### ISSUE TITLE
Support const evals on inputs in runtime

### ISSUE THREAD

**Issue by sdjordjevicTT** [tenstorrent/tt-mlir#307]
While debugging MNIST inference, I observed a transpose operation in the linear layer. I noticed that in some of the tt-forge passes(seems to be consteval), we move this transpose up into the weight parameter. When we lower to TTIR, the inputs are already transposed, so we end up generating a flatbuffer that accepts transposed inputs. However, when we push the real non-transposed inputs, we encounter errors as this seems to be currently unsupported by our runtime.

**Comment by nvukobratTT** [comment]
This was part of runtime transform logic. It'll be good to have similar support for our current runtime(s) as well! :))

**Comment by nsmithtt** [comment]
@sdjordjevicTT, this issue should be filed under tt-forge.  tt-forge owns consteval and the FE runtime side will have to manage this.

**Comment by nsmithtt** [comment]
Filed forge issue: https://github.com/tenstorrent/tt-forge/issues/43
