### ISSUE TITLE
Update python module with transformation functionality

### ISSUE THREAD

**Issue by vprajapati-tt** [tenstorrent/tt-mlir#314]
**Delta Planned**
- Call `ttir-to-ttnn-backend-pipeline` pass in Python, so just pybind the functionality over.
- "Heavily Inspired" by [TT-Forge](https://github.com/tenstorrent/tt-forge/blob/main/pybuda/csrc/passes/mlir_passes.cpp)

**Comment by odjuricicTT** [comment]
@vprajapati-tt Can we consider this finished?

**Comment by vprajapati-tt** [comment]
@odjuricicTT Yeah the pipelines were migrated over and we've moved far beyond this functionality haha. I'll mark this as closed.
