### ISSUE TITLE
Support Kernel Arguments

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#361]
We need the ability to pass kernel arguments to ttmetal programs.

```
table RuntimeArgTensorAddress {    
  global_id: uint32;    
}    
    
union RuntimeArg {    
  RuntimeArgTensorAddress,    
}    
    
table KernelDesc {    
  kernel: Kernel;    
  core_range_set: [Dim2dRange];    
  cbs: [CBRef];    
  runtime_args: [RuntimeArg];    
  debug_info: string;    
}
```

So far the only useful one I can come up with is TensorAddress which should dynamically lookup the tensor's runtime buffer address and plumb it into API:
```c++
void SetRuntimeArgs(Device* device, const std::shared_ptr<Kernel> kernel, const std::vector< CoreCoord > & core_spec, const std::vector<std::shared_ptr<RuntimeArgs>> runtime_args);
```

**Comment by kmabeeTT** [comment]
After some offline discussion, arrived at this interface in flatbuffer for compiler to fill out:

```
+table RuntimeArgTensorAddress {
+  operand_idx: uint32;
+}
+
+table RuntimeArgSemaphoreAddress {
+  initial_value: uint32;
+  core_type: CoreType;
+}
+
+union RuntimeArg {
+  RuntimeArgTensorAddress,
+  RuntimeArgSemaphoreAddress,
+}
+
 table KernelDesc {
   kernel: Kernel;
   core_range_set: [Dim2dRange];
   cbs: [CBRef];
+  runtime_args: [RuntimeArg];
   debug_info: string;
 }
 ```
 
Briefly considered and implemented version where all runtime args from compiler also same with `runtime_arg_idx: uint32` to denote the actual index in the `uint32_t` vector of rt-args given to metal where runtime would first create a map (and check for gaps, disallowed) and then convert to vector, but it was decided to keep things simple here and assume the runtime args are wrtitten to device in the same order they are received from compiler.
  
In the case of `RuntimeArgTensorAddress` runtime will replace with arg with dynamically calculated tensor address of the `operand` as given by `operand_idx`.

In the case of `RuntimeArgSemaphoreAddress`, runtime will replace with arg with value (id/address) returned from call to `CreateSemaphore()` for the Kernel's CoreRange on the desired `CoreType`.

Did some local testing, and opened PR.
