### ISSUE TITLE
Documentation in build.html Missing Information on Required Environment Variables

### ISSUE THREAD

**Issue by maychair** [tenstorrent/tt-mlir#372]
Hi,

I'm encountering an issue while building tt-mlir. The build process fails with errors indicating that the environment variables TTMLIR_VENV_DIR and TTMLIR_TOOLCHAIN_DIR are missing when using custom paths. However, the build succeeds when these variables are set.

Could you please update the documentation to include guidance on how to properly set these environment variables?

Thank you!

**Comment by nsmithtt** [comment]
Hi @maychair, please let me know if the following section of docs is what you're looking for:

https://docs.tenstorrent.com/tt-mlir/build.html#build

The relevant command that manages those environment variables for you is:
```bash
source env/activate
```

Please reopen if this doesn't resolve the issue.  Thanks!
