### ISSUE TITLE
FIXME: Hardcoded data type size

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#414]
There is a FIXME: Hardcoded data type size in file `runtime/include/tt/runtime/detail/ttmetal.h`

**Comment by ddilbazTT** [comment]
What's the calculation needed for pageSize?

**Comment by kmabeeTT** [comment]
@ddilbazTT  - I took a look, I think the issue here is that we want to remove the "4" and replace it with real data type size in bytes, which is 4 for "32 bit data types" but would be 2 for "16 bit data types" etc.

```
  uint64_t pageSize =
      pageShape[0] * pageShape[1] * 4; // FIXME: Hardcoded data type size
 ```
