### ISSUE TITLE
Prioritize using DPS results over SSA values

### ISSUE THREAD

**Issue by svuckovicTT** [tenstorrent/tt-mlir#435]
Running

```bash
./build/bin/ttmlir-opt --ttir-load-system-desc --ttir-layout  test/ttmlir/Dialect/TTNN/simple_multiply.mlir
```

produces an IR:
```bash
#any_device = #tt.operand_constraint<dram|l1|scalar|tile|any_device|any_device_tile>
#l1_ = #tt.memory_space<l1>
#system = #tt.memory_space<system>
#layout = #tt.layout<(d0, d1) -> (d0, d1), undef, <1x1>, memref<64x128xf32, #system>>
#layout1 = #tt.layout<(d0, d1) -> (d0, d1), undef, <1x1>, memref<64x128xf32, #l1_>>
module attributes {tt.system_desc = #tt.system_desc<[{arch = <wormhole_b0>, grid = 8x8, l1_size = 1499136, num_dram_channels = 12, dram_channel_size = 1073741824, noc_l1_address_align_bytes = 16, pcie_address_align_bytes = 32, noc_dram_address_align_bytes = 32, physical_cores = {worker = [(0, 0)] dram = [(0, 0)] eth = [(0, 0)] eth_inactive = [(0, 0)]}}], [0], [3 : i32], [<0, 0, 0, 0>]>} {
  func.func @forward(%arg0: tensor<64x128xf32, #layout>, %arg1: tensor<64x128xf32, #layout>) -> tensor<64x128xf32, #layout> {
    %0 = tensor.empty() : tensor<64x128xf32, #layout1>
    %1 = "ttir.to_layout"(%arg0, %0) : (tensor<64x128xf32, #layout>, tensor<64x128xf32, #layout1>) -> tensor<64x128xf32, #layout1>
    %2 = tensor.empty() : tensor<64x128xf32, #layout1>
    %3 = "ttir.to_layout"(%arg1, %2) : (tensor<64x128xf32, #layout>, tensor<64x128xf32, #layout1>) -> tensor<64x128xf32, #layout1>
    %4 = tensor.empty() : tensor<64x128xf32, #layout1>
    %5 = "ttir.multiply"(%1, %3, %4) <{operandSegmentSizes = array<i32: 2, 1>, operand_constraints = [#any_device, #any_device, #any_device]}> : (tensor<64x128xf32, #layout1>, tensor<64x128xf32, #layout1>, tensor<64x128xf32, #layout1>) -> tensor<64x128xf32, #layout1>
    %6 = tensor.empty() : tensor<64x128xf32, #layout>
    %7 = "ttir.to_layout"(%5, %6) : (tensor<64x128xf32, #layout1>, tensor<64x128xf32, #layout>) -> tensor<64x128xf32, #layout>
    return %7 : tensor<64x128xf32, #layout>
  }
}
```

`ttir.multiply` writes its result into `%4`. However, the following `ttir.to_layout` uses `%5` as its input operand. This should be fixes such that `ttir.to_layout` uses `%4` as its input.

I wonder if there is a mechanism to forbid using SSA values generated from DPS ops.

**Comment by svuckovicTT** [comment]
@nsmithtt thoughts?

**Comment by nsmithtt** [comment]
Hey Sasa, this isn't legal because then there is nothing capturing the dependency of the `ttir.to_layout` on the preceding `ttir.multiply`, i.e. one of the generic MLIR passes (like the canonicalizer) could move the layout before the multiply.

**Comment by svuckovicTT** [comment]
> Hey Sasa, this isn't legal because then there is nothing capturing the dependency of the `ttir.to_layout` on the preceding `ttir.multiply`, i.e. one of the generic MLIR passes (like the canonicalizer) could move the layout before the multiply.

Hmm... What if `ttir.multiply` returned an int to denote success/failure (or even if it were void return value), how would we go around the issue you mention? Or is it always the case that DPS params should also be returned from the function as result?

**Comment by nsmithtt** [comment]
> Hmm... What if `ttir.multiply` returned an int to denote success/failure (or even if it were void return value), how would we go around the issue you mentioned? Or is it always the case that DPS operands should also be returned from the function as result?

I'm not 100% sure how MLIR handles void return because it kind of breaks SSA, it might just assume than an operation can never move past a void, or maybe we have to explicitly describe the semantics, there are some hooks on the dialect to inject things like this.  But I don't think we should go down that path because then we are no longer following DPS semantics.

DPS is intentionally defined to have a 1-1 mapping of operation results and output arguments, there is a paragraph is the bufferization docs that talks more about this https://mlir.llvm.org/docs/Bufferization/#destination-passing-style.  From a pure graph perspective these sentences are important:
> Since SSA values are immutable, the operation returns a copy of the input vector with the element inserted.
> ...
> outs operands are referred to as “destinations” in the following (quotes are important as this operand isn’t modified in place but copied)

This invariant must hold true if we want to use DPS interface.  It just so happens that we will _always_ opt into the optimization described in a following paragraph:

> For every tensor result, a DPS op has a corresponding tensor operand. If there aren’t any other conflicting uses of this tensor, the bufferization can alias it with the op result and perform the operation “in-place” by reusing the buffer allocated for this “destination” input.

**Comment by nsmithtt** [comment]
I do admit it makes working with the graph a bit more cumbersome. We have these routines `getOperandThroughDPSOps` to help walk up the tree and fine the original tensor source.  There might be a better (more MLIR) way of doing that though, at the time I didn't find anything.

**Comment by svuckovicTT** [comment]
Alright, sounds good. Thanks for the bufferization links; closing the item.
