### ISSUE TITLE
Generation of collapsed linear affine map failing with 1D tensors

### ISSUE THREAD

**Issue by LPanosTT** [tenstorrent/tt-mlir#461]
In file `lib/Dialect/TT/IR/TTOpsTypes.cpp` the assertion on line 208 fails. The reason seems to be that the default `collapseIntervals` variable is passed which has `{start: 0, end: -1}`. And so, when a 1D tensor is passed we add 1 to `end` giving us `end = 0`, and so the assertion fails.

**Comment by svuckovicTT** [comment]
Ah, I seem to have opened a duplicate: #471
