### ISSUE TITLE
Create an analysis pass for choosing grid shape

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#49]
This will have to be a very primitive pass for the time being, but I think this issue should be used as an exercise for creating the boilerplate for an optimization pass.

Let's try to understand the MLIR way of doing this by having an analysis pass run: MLIR analysis pass: https://mlir.llvm.org/docs/Tutorials/DataFlowAnalysis/.

Definitely take a look at llvm-project source for other examples.

Separately, we should have a "dumb" pass that accepts the output from the analysis pass and applies the result.  I think we should strive to frame all of our optimization passes in this way, they should all run in 2 phases:
- Complicated analysis pass, treats graph as immutble
- Application pass that blindly does whatever the result from the analysis pass says to do

As a first step, let's take our 1x1 eltwise binary and try to put it on more cores.

**Comment by staylorTT** [comment]
This should have been resolved with #115 seems like there is a bug where linking isn't working between these two.

**Comment by nobradovictt** [comment]
> This should have been resolved with #115 seems like there is a bug where linking isn't working between these two.

Was just about to close it myself. Thanks!
