### ISSUE TITLE
[MNIST] Implement conversion of stablehlo.convert OP to TTIR dialect

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#503]
`stablehlo.convert` OP specification can be found [here](https://openxla.org/stablehlo/spec#convert).

This OP can be directly lowered into `ttir.to_layout` OP.

Additionally, we can detect cases where StableHLO converts tensor into the same type (for some reason they sometimes do this to convert input argument into local variable), and optimize out that case. Example:
```
func.func public @main(%arg0: tensor<512x784xf32>, ...) -> tensor<128x10xf32> {
    %0 = stablehlo.convert %arg0 : tensor<512x784xf32>
    ...
```

**Comment by mmanzoorTT** [comment]
#811 implements the case for conversion from one type to anther using `ttnn::to_layout` op.
