### ISSUE TITLE
[MNIST] Implement conversion of stablehlo.broadcast_in_dim OP to TTIR dialect

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#506]
`stablehlo.broadcast_in_dim` OP specification can be found [here](https://openxla.org/stablehlo/spec#broadcast_in_dim).

TTIR currently doesn't have a broadcast OP, but it does support broadcasting as a side effect of element wise OPs when inputs are not having a same shape. We can either add direct support in TTIR for broadcast OP, or do some smart mapping of `stablehlo.broadcast_in_dim + stablehlo.elementwise_op -> ttir.elementwise_op`. Later is obviously preferrable but maybe we will still have a need for broadcast OP in TTIR if the result is later used in some TTIR OP which doesn't support internal broadcasting.

Let's for now just map `stablehlo.broadcast_in_dim + stablehlo.elementwise_op -> ttir.elementwise_op` where we can, and then we will implement the `TTIR.BroadcastOP` if needed later.

**Comment by uazizTT** [comment]
I found this comment from the committer of elementwise_op: 

<img width="784" alt="image" src="https://github.com/user-attachments/assets/8b91cd5e-52b3-493e-ba7b-aebec1b4a983">

**Comment by mrakitaTT** [comment]
Just to document things that we discussed today:
- The best course of action would be to add `ttir.broadcast` op, convert `stablehlo.broadcast_in_dim` to `ttir.broadcast`, and then in TTIR->TTNN conversion pass to detect the pattern of `ttir.broadcast + ttir.element_wise` and discard the broadcast op. That way we will detect this pattern in one place, instead of detecting it for every input dialect conversion to TTIR.
- One thing to keep in mind is that it won't be always possible to just discard the broadcast op, for example if the broadcasted tensor is also used in some op that does not support implicit broadcasting. When we encounter such cases we will need to implement support for `ttnn.broadcast` op and allow converting `ttir.broadcast` to `ttnn.broadcast`.

**Comment by nvukobratTT** [comment]
> `stablehlo.broadcast_in_dim` OP specification can be found [here](https://openxla.org/stablehlo/spec#broadcast_in_dim).
> 
> TTIR currently doesn't have a broadcast OP, but it does support broadcasting as a side effect of element wise OPs when inputs are not having a same shape. We can either add direct support in TTIR for broadcast OP, or do some smart mapping of `stablehlo.broadcast_in_dim + stablehlo.elementwise_op -> ttir.elementwise_op`. Later is obviously preferrable but maybe we will still have a need for broadcast OP in TTIR if the result is later used in some TTIR OP which doesn't support internal broadcasting.
> 
> Let's for now just map `stablehlo.broadcast_in_dim + stablehlo.elementwise_op -> ttir.elementwise_op` where we can, and then we will implement the `TTIR.BroadcastOP` if needed later.

Hey, just a few questions on this note:
1. Is this Jax specific? Are you required to lower broadcast for one reason or another? I.e. is this something that we need to handle on FE (Jax) level, and do implicit broadcast beforehand?
1. Is there a plan for TTNN support on explicit broadcast op (e.g. ttnn.broadcast)? If it's by design that they want broadcast t obe handled by every op/kernel, then having ttnn.broadcast op will not pass. Instead, we should think about forcing fixes on ops that are missing broadcast support. 
1. Is there a plan how this broadcast will work with other op types? My concern is that we can end up in many edge cases that are op specific regarding desired broadcast support

**Comment by mrakitaTT** [comment]
> 1. Is this Jax specific? Are you required to lower broadcast for one reason or another? I.e. is this something that we need to handle on FE (Jax) level, and do implicit broadcast beforehand?

This line of numpy code:
```
outputs = jnp.dot(w, activations) + b
```
is lowered by Jax to this hlo:
```
%0 = stablehlo.convert %arg0 : tensor<512x784xf32>
%1 = stablehlo.convert %arg4 : (tensor<128x784xui8>) -> tensor<128x784xf32>
%2 = stablehlo.dot_general %0, %1, contracting_dims = [1] x [1], precision = [DEFAULT, DEFAULT] : (tensor<512x784xf32>, tensor<128x784xf32>) -> tensor<512x128xf32>
%3 = stablehlo.transpose %2, dims = [1, 0] : (tensor<512x128xf32>) -> tensor<128x512xf32>
%4 = stablehlo.broadcast_in_dim %arg1, dims = [1] : (tensor<512xf32>) -> tensor<1x512xf32>
%5 = stablehlo.broadcast_in_dim %4, dims = [0, 1] : (tensor<1x512xf32>) -> tensor<128x512xf32>
%6 = stablehlo.add %3, %5 : tensor<128x512xf32>
```
Of course we could explicitely expand biases tensor in Jax to avoid having broadcast op in hlo, but long term we will probably need to support the broadcast op conversion :)

Another example, this line of numpy code:
```
jnp.maximum(0, x)
```
is lowered by Jax to this hlo:
```
%cst = stablehlo.constant dense<0.000000e+00> : tensor<f32>
%7 = stablehlo.broadcast_in_dim %cst, dims = [] : (tensor<f32>) -> tensor<128x512xf32>
%8 = stablehlo.maximum %7, %6 : tensor<128x512xf32>
```

> 2. Is there a plan for TTNN support on explicit broadcast op (e.g. ttnn.broadcast)? If it's by design that they want broadcast t obe handled by every op/kernel, then having ttnn.broadcast op will not pass. Instead, we should think about forcing fixes on ops that are missing broadcast support.
> 3. Is there a plan how this broadcast will work with other op types? My concern is that we can end up in many edge cases that are op specific regarding desired broadcast support

We haven't talked with anyone from Metal team yet, but our current plan is to only support cases where we can combine broadcast + eltwise ops to ttnn ops which support implicit broadcasting, and to return conversion failure if we encounter other cases (like the situation I mentioned in [this comment](https://github.com/tenstorrent/tt-mlir/issues/506#issuecomment-2344002593)). Then in the future if/when we do encounter such cases, we will have couple of options:
1. To add support in `metal::ttnn` for tensor broadcasting, if this is aligned with their plans.
2. If it is not aligned with their plans then as you said we can change other TTNN operations to support implicit broadcasting.
3. If Metal team is against both of these options, then we can do something with custom kernels.

Maybe there is some other option that I missed, feel free to add, I haven't thought about this that deeply since we don't yet have a need for it (at least for MNIST model) and it probably won't impact implementation for currently supported cases, at least short term.
