### ISSUE TITLE
[MNIST] Implement conversion of stablehlo.constant OP to TTIR dialect

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#507]
`stablehlo.constant` OP specification can be found [here](https://openxla.org/stablehlo/spec#constant).

Example hlo:
```
%cst_2 = stablehlo.constant dense<0.000000e+00> : tensor<f32>
```

**Comment by mrakitaTT** [comment]
I've investigated this while working on ReduceOp conversion (since ReduceOp is always preceeded by ConstantOp to create init value for the ReduceOp), and there are several things to discuss here.

### What functionality do we need in our dialects?

In MNIST model all uses of `stablehlo.constant` are producing tensor with a single element value, but `stablehlo.constant` can be also used to produce tensor of any shape with a given array of values. ONNX has a similar [constant OP](https://onnx.ai/onnx/operators/onnx__Constant.html) which can also accept array of values, but it can only produce one-dimensional tensor. It seems that if we had a functionality to create tensor with given array of values and with a given shape it would probably cover us for all input dialects.

### What TTNN OP can we use to achieve this functionality?

Currently TTNN only has functionality to create `ttnn.tensor` from `torch.tensor`, so it seems like we need to add new functionality into TTNN to create tensor with a given shape and values. We can temporarily use [`ttnn.full`](https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/full.html) to create one element tensor with a given value in order to support MNIST model, while we wait on TTNN support.

### What TTIR OP can we use to lower `stablehlo.constant` OP into?

There are several options here:
- To use [`tensor.from_elements`](https://mlir.llvm.org/docs/Dialects/TensorOps/#tensorfrom_elements-tensorfromelementsop) OP from tensor dialect, similar like we use `tensor.empty` OP.
- To use [`arith.constant`](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithconstant-arithconstantop) OP from arith dialect. Judging by their documentation this OP should produce only a single value output, but it can currently produce output of any type, therefore it can produce tensors. Still, I wouldn't go with this option because in Arith dialect source code there is a TODO for this operation which says "_Disallow arith.constant to return anything other than a signless integer or float like_".
- To create new TTIR OP that will map to the new TTNN OP that we will add to create tensors with a given shape and values. I don't see any problem with this, but it would maybe be a bit inconsistent/weird if we map tensor creation to TTIR dialect OP, and empty tensor creation to Tensor dialect OP.


@nsmithtt @sdjordjevicTT @uazizTT What do you guys think about all of this?

**Comment by nsmithtt** [comment]
I agree, on TTNN side let's lower to `ttnn.full`.

As for TTIR:
- `tensor.from_elements`: A positive for going down this path is because we use `tensor.empty` and it's an existing op that kind of does what we want.  Do you think it supports all of the other dialects use cases?  For any shape it could be a 1d `tensor.from_elements` + an explicit broadcast?
- `arith.constant`: I agree let's not go down this path.  There's also not a strong enough reason to bring in a whole new dialect in TTIR just for one op.
- `ttir.???`: This probably affords us the most flexibility and probably the direction that makes most sense long term.  It's somewhat random that `tensor.empty` is supported when none of the other ops from this dialect are supported.  Perhaps we can have a new op that handles all flavors of tensor creation, empty, scalar, broadcasted

**Comment by mrakitaTT** [comment]
> * `tensor.from_elements`: A positive for going down this path is because we use `tensor.empty` and it's an existing op that kind of does what we want.  Do you think it supports all of the other dialects use cases?  For any shape it could be a 1d `tensor.from_elements` + an explicit broadcast?

Yeah it supports all the input dialects use cases, i.e. `stablehlo.constant` and `onnx.constant` can directly be mapped to it, because it can take variadic number of input values and produce tensor filled with those values having a given shape which can be multidimensional, but that shape total size has to correspond to total size of input values. It doesn't support implicit broadcasting, i.e. filling as `ttir.empty` or `ttnn.full` do, so far as I've seen everybody do it in multiple steps, first they construct tensor with initial value and then do explicit broadcastings after that. We can recognize that pattern and match it in TTIR->TTNN conversion to `ttnn.empty`/`ttnn.full` in case when single value is used to fill the initial tensor.

> * `arith.constant`: I agree let's not go down this path.  There's also not a strong enough reason to bring in a whole new dialect in TTIR just for one op.

We actually already support `arith` dialect, i.e. we register it in our dialects registration func, which is the reason why I considered it. But yeah, it's the worst solution here.

> * `ttir.???`: This probably affords us the most flexibility and probably the direction that makes most sense long term.  It's somewhat random that `tensor.empty` is supported when none of the other ops from this dialect are supported.  Perhaps we can have a new op that handles all flavors of tensor creation, empty, scalar, broadcasted

We can have some swiss army `ttir.create_tensor` OP which takes `fill_value` and `input_values` arguments, where only one of those should be passed in, and then depending on those arguments it can create all kinds of tensors we need. If `fill_value` is passed and value is 0 then we convert it to `ttnn.empty`, if passed `fill_value` is not 0 then we convert it to `ttnn.full`, and if `input_values` is passed then we convert it to some new ttnn OP that should be added for this purpose. If `input_values` is passed we should require that size of `input_values` matches total size of output tensor shape.

One issue that I have with this approach is that we cannot directly map from input dialects to `ttir.create_tensor` OP with `fill_value` != 0, so we would have to do the pattern matching during each input dialect conversion to figure this out. I think it might make more sense to go with `tensor.empty`+`tensor.from_elements` approach, because those directly map to input dialects OPs, and then we can do this pattern matching in one place during TTIR->TTNN conversion. Ofc we can also have TTIR OP that does only what `tensor.from_elements` does, but then what's the point of using `tensor.empty` and mixing dialects.

What do you guys think?

FYI @AleksKnezevic

**Comment by nsmithtt** [comment]
Hey Marko I agree with everything you're saying.  I think it makes sense to keep `empty` and `fill` separate, ideally empty maps to tensor allocation and no work is actually done, whereas fill actually does memory initialization.  I agree it seems a bit arbitrary that we only support `tensor.empty`, afaict the linalg and tosa dialects do the same thing.

I'm actually leaning towards keeping `tensor.empty` the way it is and having an explicit `ttir.fill` op that takes an empty tensor + fill value.  This keeps things consistent with DPS style.  We can separately decide if we want to replace `tensor.empty` with `ttir.empty`.  What do you think?

**Comment by nsmithtt** [comment]
FYI @rpavlovicTT since you filed related issue #231

**Comment by mrakitaTT** [comment]
> I'm actually leaning towards keeping tensor.empty the way it is and having an explicit ttir.fill op that takes an empty tensor + fill value. This keeps things consistent with DPS style. We can separately decide if we want to replace tensor.empty with ttir.empty. What do you think?

@nsmithtt I have no issues with having a `ttir.fill` op in general, we can have it to make TTIR dialect more robust, but I don't think it is the op that we should use in this conversion. StableHLO and ONNX do not have a concept of "fill" op, they use a combination of constant tensor creation + broadcast, so if we wanted to detect this pattern and do the conversion to `ttir.fill` we would have to do it separately for each input dialect conversion. We had a discussion about pattern matching where we agreed that it would be better to strive to do pattern matching during TTIR->TTNN conversion so it is done only in one place. From that perspective I think it is better in addition to `ttir.fill` op to also have some `ttir.constant` op (or use `tensor.from_elements` op) which is mapping directly to `stablehlo.constant` and `onnx.constant`. It only creates tensor from input values, without filling i.e. broadcasting to multiple dimensions. And then we pattern match `ttir.empty + ttir.constant + ttir.broadcast` to `ttnn.fill`. Or do you think it is making our TTIR dialect too broad and that we should still better do the pattern matching before TTIR in this case and convert directly to `ttir.fill`? I personally see no issues with having all three flavors in TTIR (`ttir.empty`, `ttir.fill`, `ttir.constant`).

**Comment by nsmithtt** [comment]
So I can't really find this clearly stated in their spec, but I did find [this example](https://openxla.org/stablehlo/spec#programs):
```mlir
%3 = "stablehlo.constant"() {value = dense<0.0> : tensor<1x10xf32>} : () -> tensor<1x10xf32>
```

This appears to implicitly broadcast.  `tosa.const` seems [similarly spec'd](https://mlir.llvm.org/docs/Dialects/TOSA/#tosaconst-mlirtosaconstop), where `value` is an `mlir::ElementsAttr`.

Perhaps we should just copy tosa?  We can hold off on `ttir.fill` then, so now we have 2 ways to create a tensor:
- `tensor.empty`: Stays the same / keeps the same semantics
- `ttir.const`/`ttir.constant`: New op with same semantics as stablehlo/tosa const.  Ideally we can adopt using `mlir::ElementsAttr` for the value attribute as well.  This op has the additional benefit that we can mark the op as having trait `ConstantLike` and it can opt into MLIR constant folding.

**Comment by mrakitaTT** [comment]
> So I can't really find this clearly stated in their spec, but I did find [this example](https://openxla.org/stablehlo/spec#programs):
> 
> ```mlir
> %3 = "stablehlo.constant"() {value = dense<0.0> : tensor<1x10xf32>} : () -> tensor<1x10xf32>
> ```

Wow, yeah I was looking only at the specs and their [test examples](https://github.com/openxla/stablehlo/blob/main/stablehlo/tests/interpret/constant.mlir) so I didn't know they support this, it's weird that they didn't even add one test example of that. Seems like Jax folks are also not aware since this is how they produce tensor of zeroes: 
```
%cst = stablehlo.constant dense<0.000000e+00> : tensor<f32>
%7 = stablehlo.broadcast_in_dim %cst, dims = [] : (tensor<f32>) -> tensor<128x512xf32>
```

> Perhaps we should just copy tosa? We can hold off on `ttir.fill` then, so now we have 2 ways to create a tensor:
> 
> * `tensor.empty`: Stays the same / keeps the same semantics
> * `ttir.const`/`ttir.constant`: New op with same semantics as stablehlo/tosa const.  Ideally we can adopt using `mlir::ElementsAttr` for the value attribute as well.  This op has the additional benefit that we can mark the op as having trait `ConstantLike` and it can opt into MLIR constant folding.

I agree, let's move forward with this if nobody else objects.

**Comment by mrakitaTT** [comment]
@nsmithtt One thing that we forgot to discuss today is if we want to allow `ttir.fill` to take tensor with multiple values on the input, to support cases like this:
```
%0 = "stablehlo.constant"() {value = dense<[0.2, 1.3]> : tensor<2xf32>} : () -> tensor<2xf32>

// Would map to:
%0 = tensor.empty() : tensor<2xf32>
%1 = "ttir.fill"(%0) {value = dense<[0.2, 1.3]> : tensor<2xf32>} : () -> tensor<2xf32>
```

That way `ttir.fill` would behave completely like `stablehlo/tosa/onnx.constant` OP, with only difference that it would be in DPS style.

We can't currently lower this case to TTNN, because `metal::ttnn` API is missing functionality to create tensor with given multiple values (except from torch tensor), but we don't need it yet (at least for MNIST model).

**Comment by nsmithtt** [comment]
Yeah that's a good point, the multiple values thing definitely throws a wrench in the fill idea.  And it does make constant folding a bit awkward.  So after a lot of back and forth, I think the most natural thing is to just have `ttir.constant` tensor creation after all.  This will be lowered in 2 ways to TTNN:
- Single value bcasted can be lowered to TTNN full
- Multi value initialization is a constant tensor embedded in flatbuffer and uploaded by the host
