### ISSUE TITLE
Enforce no direct push to main

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#52]

**Comment by vmilosevic** [comment]
I need aditional permissions set to my account to be able to manage this. It needs to be either an admin role or a custom role with the "edit repository rules" permission.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

**Comment by nsmithtt** [comment]
@staylorTT, can you work with John to set this up?

**Comment by vmilosevic** [comment]
Settings are applied, closing issue
