### ISSUE TITLE
CI Action Items remaining

### ISSUE THREAD

**Issue by tapspatel** [tenstorrent/tt-mlir#525]
Feel free to make separate issues for this. Writing it down for tracking:

- setup builders and consolidate “self hosted” onto builders (builder-1, builder-2, builder-3, builder-4)
- setup n300-4
- migrate building into one location (currently, happens in build-docker.yml and build-and-test.yml)
- make ttrt whl smaller (only include files that are necessary)
- action variable for compile flags when building

Add in remaining machines

- n150-6
- n300-5
- builder-5

**Comment by vmilosevic** [comment]
Tasks

- [ ] setup builders and consolidate “self hosted” onto builders (builder-1, builder-2, builder-3, builder-4)
- [ ] setup n300-4
- [ ] migrate building into one location (currently, happens in build-docker.yml and build-and-test.yml)
- [ ] make ttrt whl smaller (only include files that are necessary)
- [ ] action variable for compile flags when building

Add in remaining machines

- [ ] n150-6
- [ ] n300-5
- [ ] builder-5

**Comment by vmilosevic** [comment]
Created tickets

- [ ] https://github.com/tenstorrent/tt-mlir/issues/590
- [ ] https://github.com/tenstorrent/tt-mlir/issues/591
- [ ] https://github.com/tenstorrent/tt-mlir/issues/592
