### ISSUE TITLE
Tensor Dealloc Op

### ISSUE THREAD

**Issue by jnie-TT** [tenstorrent/tt-mlir#553]
With tensors stored in L1 by default, it would be desirable to have a dealloc op that deallocates the tensors dynamically. Currently all tensors are deallocated at the end of program execution, which is not ideal and may cause insufficient L1 memory issues.

Assigning to @nobradovictt for now, please feel free to reassign.

**Comment by odjuricicTT** [comment]
There seems to be a [DeallocOp](https://github.com/tenstorrent/tt-mlir/blob/main/include/ttmlir/Dialect/TTNN/IR/TTNNOps.td#L339) in TTNN IR.
Are we only missing support in runtime?

**Comment by nsmithtt** [comment]
We have TTNN dealloc op too, I think we are missing a test that emits an explicit deallocate + runtime support

**Comment by jnie-TT** [comment]
Talked with @nobradovictt offline, just like @nsmithtt said, we're missing the emission + runtime support for the dealloc op. This task is covered by #576 . I'll close this ticket as it is redundant.

**Comment by nobradovictt** [comment]
@jnie-TT Do we need a separate issue for runtime support? It might be good to first just add runtime support with simple test using alloc+dealloc. Related issue will focus on generating it E2E for every model/test where Optimizer is used.

**Comment by jnie-TT** [comment]
> @jnie-TT Do we need a separate issue for runtime support? It might be good to first just add runtime support with simple test using alloc+dealloc. Related issue will focus on generating it E2E for every model/test where Optimizer is used.

Created ticket here #598
