### ISSUE TITLE
[Bug] Reciprocal op requires 2 inputs instead of 1

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-mlir#562]
Seems like reciprocal is defined as eltwise binary, instead of eltwise unary on TTIR to TTNN level. Therefore, we're enforcing 2 input requirements instead of one. 

Error sample:
```
E       RuntimeError: TT_FATAL @ /localdev/nvukobrat/tt-forge-fe/third_party/tt-mlir/runtime/lib/ttnn/program.cpp:494: program->inputs()->size() == inputs.size()
E       info:
E       Program expects 2 inputs, found 1 in input tensors vector
```

**Comment by sdjordjevicTT** [comment]
Can you show us what test you are trying to run?

Reciprocal op is defined as element-wise unary in both TTIR and TTNN dialects:

- [TTIR Reciprocal Op](https://github.com/tenstorrent/tt-mlir/blob/e795e09c45c4e26c22eeb2ce0b8380d5607093a0/include/ttmlir/Dialect/TTIR/IR/TTIROps.td#L249)
- [TTNN Reciprocal Op](https://github.com/tenstorrent/tt-mlir/blob/e795e09c45c4e26c22eeb2ce0b8380d5607093a0/include/ttmlir/Dialect/TTNN/IR/TTNNOps.td#L100)

**Comment by nvukobratTT** [comment]
> Can you show us what test you are trying to run?
> 
> Reciprocal op is defined as element-wise unary in both TTIR and TTNN dialects:
> 
> * [TTIR Reciprocal Op](https://github.com/tenstorrent/tt-mlir/blob/e795e09c45c4e26c22eeb2ce0b8380d5607093a0/include/ttmlir/Dialect/TTIR/IR/TTIROps.td#L249)
> * [TTNN Reciprocal Op](https://github.com/tenstorrent/tt-mlir/blob/e795e09c45c4e26c22eeb2ce0b8380d5607093a0/include/ttmlir/Dialect/TTNN/IR/TTNNOps.td#L100)

I'm having issues connecting to VPN to provide detailed results, but as recall the issue could be caused by this part:
```third_party/tt-mlir/lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp```, more specifically: `populateTTIRToTTNNPatterns`.

**Comment by nvukobratTT** [comment]
Also, test that I'm running is on FFE side, still waiting for approval in order to be merged. But for quick check, feel free to cherry pick these two commits:
- git cherry-pick c86a1f64612bec0a7f095a08a8c657d508e70c13 ([ref](https://github.com/tenstorrent/tt-forge-fe/pull/202/commits))
- git cherry-pick a8bac9fad837d094a4324d0bd978cce57e1ecbcd ([ref](https://github.com/tenstorrent/tt-forge-fe/pull/203/commits))

**Comment by sdjordjevicTT** [comment]
Can you provide the reportify graph for this test case?

I have a suspicion that this test translates to addition with a constant, and it seems that constants aren't yet supported in the forge-fe->tt-mlir lowering, as you've discovered. This is probably why you're getting the message because the model you've defined has 2 inputs, but we need to verify this on the Reportify graph.

**Comment by sdjordjevicTT** [comment]
As per our offline discussion, the Forge Compiler must support the passing of the constant inputs. I will close this for now. In order to fully work with constants, we need to support a constant op in TT-MLIR. The task already exists: https://github.com/tenstorrent/tt-mlir/issues/231
