### ISSUE TITLE
[TTIR][Pass] All transforms passes are mixed together.

### ISSUE THREAD

**Issue by mingzheTerapines** [tenstorrent/tt-mlir#568]
As a newcomer to the TT-MLIR project, I'm currently exploring the ttir transform passes. I've also been contributing to the CIRCT project, and I have an idea that could enhance the readability and maintainability of our codebase.

I propose that we consider separating the passes into distinct C++ files. Currently, having all passes in a single passes.cpp file can be less elegant and challenging to navigate for readers. A more organized approach would be to structure the files according to the definitions in passes.td.

By doing so, we can align with best practices for code clarity and ease of understanding, which would be beneficial for both new contributors and existing team members.

Thank you for considering this suggestion. I'm looking forward to working together to improve our project.
Also, my team just wrote some documents in Chinese for TT-MLIR project:https://1nfinite.ai/t/tt-mlir-tenstorrent-mid-level/125

**Comment by sdjordjevicTT** [comment]
Thank you for your suggestion, @mingzheTerapines, and for your contribution. I agree that separating the passes into distinct C++ files could improve the readability and maintainability of the codebase. I will move this issue under the "MLIR Dialect \ Passes" component so we can take a look at it.

Regarding the documents in Chinese, I appreciate the effort your team has put into creating them!

We are also looking forward to collaborating further to enhance the project!

@nsmithtt @mtopalovicTT @svuckovicTT @rpavlovicTT
FYI for other MLIR owners in the TT-MLIR repository

**Comment by mingzheTerapines** [comment]
@sdjordjevicTT We are thrilled to contribute to the TTMLIR project. We have purchased several `wormhole_0` and `grayskull` computing cards for experimental purposes. Could you tell us how we can further assist the project?

Additionaly, we are in the process of designing and developing a graph compiler named MAGIC (https://1nfinite.ai/t/topic/110), which utilizes the optimized Flow IR from IREE as the frontend and employs computing cards such as Tenstorrent as the backend. The following image illustrates our experimental translation pathway, depicting the deployment process of the `linalg.matmul` operator onto Tenstorrent cards. 
![image](https://github.com/user-attachments/assets/f94d6eb1-b981-40d9-a0c6-e67fdcc3c174)
![image](https://github.com/user-attachments/assets/8ebdb278-332b-4c3a-9ddf-147249618b5a)

**Comment by nsmithtt** [comment]
Hi @mingzheTerapines, this sounds like a very interesting project!  We have also discussed the prospect of implementing an IREE backend and supporting linalg dialect, but no plans to do so in the short term.

In the short term our efforts are focused on bootstrapping the compiler and targeting TTNN as a backend target, we hope to have more interesting results to share in the coming months.  In the medium term, we would like to hook into more of the existing MLIR ecosystem and support some of the pre-existing tensor dialects.  Linalg specifically is one we would like to eventually support, but requires some foundational work to be in place before we are ready to start taking this on.

Is there a particular subset of ops from the linalg dialect that you are most interested in?

In the meantime we would be happy to support you to the best of our ability and are willing to review/accept pull requests.  Let us get back to you on how you can support us, we need to establish a process for external contributions, but likely we can label issues as good ones for external contributors to take on.

We look forward to collaborating with you!

**Comment by mingzheTerapines** [comment]
Dear @nsmithtt , here is a PR(https://github.com/tenstorrent/tt-mlir/pull/615) from us.
Yes, this project do need a process for external contributions like us.

**Comment by nsmithtt** [comment]
PR merged, thank you! :)

**Comment by sdjordjevicTT** [comment]
We agreed on a refactor that can split the current set of passes into the following cpp files:
- Transforms/Utils.cpp
  - ImplicitDevice
  - LoadSystemDesc
- Transforms/Transforms.cpp
   - SlidingWindow2DFixShapes
- Transforms/Optimizer.cpp
    - Optimizer
- Transforms/Generic.cpp
    - GenericKernel
    - GenericRegion
    - GenericRegionOperandsToMemref
- Transforms/Layout.cpp
    - Layout
    - SplitCompoundLayout
- Transforms/Allocate.cpp
    - Allocate

**Comment by mingzheTerapines** [comment]
@sdjordjevicTT We are delighted to hear about the upcoming refactoring of the program. Recently, your colleagues in China have contacted us, mentioning that there will be a meeting for further discussion. We are looking forward to it with great anticipation. =）

**Comment by mingzheTerapines** [comment]
Cool passes are much more firendly =)
