### ISSUE TITLE
Appearance of PyBuda/Buda keywords in MLIR

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-mlir#569]
There are few files where we're getting PyBuda/Buda appearing. We should probably correct those to Forge if they're not referencing old compiler stack. Few file samples:
```
tt-forge-fe/third_party/tt-mlir/docs/src/build.md
tt-forge-fe/third_party/tt-mlir/docs/src/overview.md
tt-forge-fe/third_party/tt-mlir/docs/src/specs/runtime-stitching.md
tt-forge-fe/third_party/tt-mlir/test/ttmlir/Dialect/TTNN/multiple_add_with_loc_grid_override.mlir
tt-forge-fe/third_party/tt-mlir/test/ttmlir/Dialect/TTNN/multiple_add_with_loc.mlir
```

**Comment by nvukobratTT** [comment]
@sdjordjevicTT let me know if yu would like for someone from FFE to correct this. We're currently pushing rename on FFE side, so we can probably easily correct those on MLIR as well.

**Comment by sdjordjevicTT** [comment]
No worries, here is the PR:
https://github.com/tenstorrent/tt-mlir/pull/595
