### ISSUE TITLE
Reduce ttrt whl size

### ISSUE THREAD

**Issue by vmilosevic** [tenstorrent/tt-mlir#591]
@tapspatel 
make ttrt whl smaller (only include files that are necessary)

**Comment by tapspatel** [comment]
Current ttrt installation size: 940MB
718MB	tt_metal/
84MB	ttnn
24MB	tests
67MB	_ttnn.so
36MB	built/
Time to install: 1min 40 seconds

**Comment by tapspatel** [comment]
reduced tt_metal to 236MB

**Comment by tapspatel** [comment]
time to install: 1min 10 seconds
size: 448MB

**Comment by tapspatel** [comment]
```
root@0b105f1e99a0:/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime# du -sh * | sort
1.5M	libdevice.so
1.7M	capture-release
144K	runtime
2.0M	csvexport-release
20K	generated
232K	libuv.so.1
236M	tt_metal
23M	tests
3.0M	_C.cpython-310-x86_64-linux-gnu.so
3.1M	libtt_metal.so
34M	built
4.0K	__init__.py
432K	libtracy.so.0.10.0
560K	libnng.so.1
64M	_ttnn.so
8.0K	__pycache__
80M	ttnn
```

**Comment by tapspatel** [comment]
reduced tt_metal to 160MB
size: 372 MB
time to install: 1 min

**Comment by tapspatel** [comment]
size: 317 MB
time to create wheel: 1 min
time to install wheel: 4 seconds
