### ISSUE TITLE
[Ops] Add TTIR isfinite OP

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#634]
We should add `isfinite` OP to TTIR and TTNN dialects and then map it to [ttnn.isfinite](https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/isfinite.html) OP.

**Comment by sdjordjevicTT** [comment]
Can we please open ops tasks under the MLIR Dialect / Passes component to consolidate them into one place? There were a few cases when few folks were working on the same op, hence I want to avoid that.

**Comment by mrakitaTT** [comment]
@sdjordjevicTT Sure, sorry about that! We've also had couple instances of folks working on the same op either because they forget to assign themselves to issue or they open separate duplicate issue etc, so I totally understand the pain. This op in particular was one of those :) We've recently had a push through the whole list of StableHLO ops and we've opened task for each under `StableHLO Conversion` component, so that we have unique list people can take tasks from. Those tasks encompass whole process of supporting StableHLO op: adding tests in frontends, implementing conversion from StableHLO, making necessary changes in TTIR/TTNN, changes in runtime, etc. Ideally we should've opened separate tasks for each part of the work but we wanted to have this list asap and also it would be hard to track effort completion across multiple repos/components. We can now open separate tasks for each op that requires changes in TTIR/TTNN under `MLIR Dialect / Passes` component, let me talk with @AleksKnezevic to figure out how best to get to this.
