### ISSUE TITLE
Run `pybuda/test/fx/test_ops.py::test_add`

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#68]
This is the simple-test we should run e2e to declare M0 finished.  It will exercise a simple single eltwise op going through tt-mlir compile and then running it through the device runtime.

```
pytest -svv pybuda/test/fx/test_ops.py::test_add
```

**Comment by pilkicTT** [comment]
All related issues are completed. 

**NOTE: the test has been changed to:**
```pytest -svv pybuda/test/mlir/test_ops.py::test_add```
