### ISSUE TITLE
Add CCL Ops to TTNN Dialect

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#700]
- `ttnn.all_gather`
- `ttnn.line_all_gather`
- `ttnn.reduce_scatter`

Please mirror TTNN op interface.

**Comment by gfengTT** [comment]
Just noticed `linear_all_gather` has been consolidated into `all_gather` (https://github.com/tenstorrent/tt-metal/commit/a19c57ae03aef35bb615c1c087ddcce257ce8d1e).

**Comment by nsmithtt** [comment]
Good catch, I think that just simplifies our op set?
