### ISSUE TITLE
Disable optimizer with flag, instead of just sharding pass

### ISSUE THREAD

**Issue by odjuricicTT** [tenstorrent/tt-mlir#727]

**Comment by odjuricicTT** [comment]
This seems to be a blocker for model bringup. Will prioritize.

**Comment by vcanicTT** [comment]
> This seems to be a blocker for model bringup. Will prioritize.

Ok, I'll take a look.

**Comment by vcanicTT** [comment]
Let's discuss tomorrow in the morning.
