### ISSUE TITLE
[LLAMA] Implement conversion of stablehlo.concatenate to TTIR

### ISSUE THREAD

**Issue by mmanzoorTT** [tenstorrent/tt-mlir#751]
`stablehlo.concatenate` OP specification can be found [here](https://openxla.org/stablehlo/spec#concatenate).

**Comment by AleksKnezevic** [comment]
Please add silicon test and e2e test in tt-xla.

**Comment by ddilbazTT** [comment]
@AleksKnezevic @nsmithtt I noticed stablehlo uses si64 for dimension but ttnn.concat uses si32 for dimension.
https://openxla.org/stablehlo/spec#concatenate 

Should I:
1) Cast si64 to si32 before passing into ttnn.concat?
2) Change ttnn.concat dimension to use si64?

**Comment by nsmithtt** [comment]
@ddilbazTT good question, go ahead and cast it to si32.
