### ISSUE TITLE
Unpadding Issue in tt-mlir

### ISSUE THREAD

**Issue by pdeviTT** [tenstorrent/tt-mlir#813]
## Description

**Job name:** [test_transpose[params5]](https://github.com/tenstorrent/tt-forge-fe/actions/runs/10956249916/job/30423853615)

**Regression commit:** 19732d0b2a10b053109d41243a29f95acc9cbabe

**Failure reason:** 
```
Can only unpad to row major tensor of even width
TT_FATAL @ /proj_sw/user_dev/pdevi/FFE/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/data_movement/untilize_with_unpadding/device/untilize_with_unpadding_op.cpp:25: ((this->output_tensor_end[-1] + 1) % 2 == 0)
```

## Reproduce

To reproduce, you can refer to this [job](https://github.com/tenstorrent/tt-forge-fe/actions/runs/10956249916/job/30423853615).

For full repro, the test case should run in the FFE repo. Follow this project build [instruction](https://docs.tenstorrent.com/tt-forge-fe/build.html) before you run.

Run command sample:
```bash
pytest forge/test/mlir/test_ops.py::test_transpose[params5] -vss
```

Also, for quicker repro, you can refer to this TTIR for a single failure example:
```bash
module @Transpose attributes {tt.system_desc = #tt.system_desc<[{arch = <wormhole_b0>, grid = 8x8, l1_size = 1499136, num_dram_channels = 12, dram_channel_size = 1073741824, noc_l1_address_align_bytes = 16, pcie_address_align_bytes = 32, noc_dram_address_align_bytes = 32, l1_unreserved_base = 1024, erisc_l1_unreserved_base = 1024, dram_unreserved_base = 1024, dram_unreserved_end = 1073741824, physical_cores = {worker = [ 0x0,  0x1,  0x2,  0x3,  0x4,  0x5,  0x6,  0x7,  1x0,  1x1,  1x2,  1x3,  1x4,  1x5,  1x6,  1x7,  2x0,  2x1,  2x2,  2x3,  2x4,  2x5,  2x6,  2x7,  3x0,  3x1,  3x2,  3x3,  3x4,  3x5,  3x6,  3x7,  4x0,  4x1,  4x2,  4x3,  4x4,  4x5,  4x6,  4x7,  5x0,  5x1,  5x2,  5x3,  5x4,  5x5,  5x6,  5x7,  6x0,  6x1,  6x2,  6x3,  6x4,  6x5,  6x6,  6x7,  7x0,  7x1,  7x2,  7x3,  7x4,  7x5,  7x6,  7x7] dram = [ 8x0,  9x0,  10x0,  8x1,  9x1,  10x1,  8x2,  9x2,  10x2,  8x3,  9x3,  10x3]}, supported_data_types = [<f32>, <f16>, <bf16>, <bfp_f8>, <bfp_bf8>, <bfp_f4>, <bfp_bf4>, <bfp_f2>, <bfp_bf2>, <u32>, <u16>, <u8>], supported_tile_sizes = [ 4x16,  16x16,  32x16,  4x32,  16x32,  32x32]}], [0], [3 : i32], [ 0x0x0x0]>} {
  func.func @forward(%arg0: tensor<6x33x34xf32> {ttir.name = "a"}) -> (tensor<6x34x33xf32> {ttir.name = "Transpose.output_transpose_0"}) {
    %0 = tensor.empty() : tensor<6x34x33xf32>
    %1 = "ttir.transpose"(%arg0, %0) <{dim0 = -2 : si32, dim1 = -1 : si32, operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<6x33x34xf32>, tensor<6x34x33xf32>) -> tensor<6x34x33xf32>
    return %1 : tensor<6x34x33xf32>
  }
}
```

## Observed behavior

This test case is passing in this commit "f78d9d798994a1404d752e7ee6e8e9f52d9d3004" but failing in this commit "abb97a9b3e0f17b569438fcabf5d56d4e48f0bf5". It was regressed in this commit "19732d0b2a10b053109d41243a29f95acc9cbabe". We are getting same issue for other 144 cases, which was listed below.

1. test_greater_equal[dims1]
2. test_greater_equal[dims2]
3. test_reduce_sum[-1-32]
4. test_reduce_sum[-1-64]
5. test_reduce_sum[-1-128]
6. test_reduce_mean[-1-input_shape3]
7. test_reduce_mean[-1-input_shape4]
8. test_reduce_mean[-1-input_shape5]
9. test_matmul[1-7-7-1]
10. test_matmul[1-7-7-7]
11. test_matmul[1-7-7-32]
12. test_matmul[1-7-32-1]
13. test_matmul[1-7-32-7]
14. test_matmul[1-7-32-32]
15. test_matmul[1-7-41-1]
16. test_matmul[1-7-41-7]
17. test_matmul[1-7-41-32]
18. test_matmul[1-7-64-1]
19. test_matmul[1-7-64-7]
20. test_matmul[1-7-64-32]
21. test_matmul[1-41-7-1]
22. test_matmul[1-41-7-7]
23. test_matmul[1-41-7-32]
24. test_matmul[1-41-32-1]
25. test_matmul[1-41-32-7]
26. test_matmul[1-41-32-32]
27. test_matmul[1-41-41-1]
28. test_matmul[1-41-41-7]
29. test_matmul[1-41-41-32]
30. test_matmul[1-41-64-1]
31. test_matmul[1-41-64-7]
32. test_matmul[1-41-64-32]
33. test_matmul[7-7-7-1]
34. test_matmul[7-7-7-7]
35. test_matmul[7-7-7-32]
36. test_matmul[7-7-32-1]
37. test_matmul[7-7-32-7]
38. test_matmul[7-7-32-32]
39. test_matmul[7-7-41-1]
40. test_matmul[7-7-41-7]
41. test_matmul[7-7-41-32]
42. test_matmul[7-7-64-1]
43. test_matmul[7-7-64-7]
44. test_matmul[7-7-64-32]
45. test_matmul[7-41-7-1]
46. test_matmul[7-41-7-7]
47. test_matmul[7-41-7-32]
48. test_matmul[7-41-32-1]
49. test_matmul[7-41-32-7]
50. test_matmul[7-41-32-32]
51. test_matmul[7-41-41-1]
52. test_matmul[7-41-41-7]
53. test_matmul[7-41-41-32]
54. test_matmul[7-41-64-1]
55. test_matmul[7-41-64-7]
56. test_matmul[7-41-64-32]
57. test_matmul[32-7-7-1]
58. test_matmul[32-7-7-7]
59. test_matmul[32-7-7-32]
60. test_matmul[32-7-32-1]
61. test_matmul[32-7-32-7]
62. test_matmul[32-7-32-32]
63. test_matmul[32-7-41-1]
64. test_matmul[32-7-41-7]
65. test_matmul[32-7-41-32]
66. test_matmul[32-7-64-1]
67. test_matmul[32-7-64-7]
68. test_matmul[32-7-64-32]
69. test_matmul[32-41-7-1]
70. test_matmul[32-41-7-7]
71. test_matmul[32-41-7-32]
72. test_matmul[32-41-32-1]
73. test_matmul[32-41-32-7]
74. test_matmul[32-41-32-32]
75. test_matmul[32-41-41-1]
76. test_matmul[32-41-41-7]
77. test_matmul[32-41-41-32]
78. test_matmul[32-41-64-1]
79. test_matmul[32-41-64-7]
80. test_matmul[32-41-64-32]
81. test_matmul[41-7-7-1]
82. test_matmul[41-7-7-7]
83. test_matmul[41-7-7-32]
84. test_matmul[41-7-32-1]
85. test_matmul[41-7-32-7]
86. test_matmul[41-7-32-32]
87. test_matmul[41-7-41-1]
88. test_matmul[41-7-41-7]
89. test_matmul[41-7-41-32]
90. test_matmul[41-7-64-1]
91. test_matmul[41-7-64-7]
92. test_matmul[41-7-64-32]
93. test_matmul[41-41-7-1]
94. test_matmul[41-41-7-7]
95. test_matmul[41-41-7-32]
96. test_matmul[41-41-32-1]
97. test_matmul[41-41-32-7]
98. test_matmul[41-41-32-32]
99. test_matmul[41-41-41-1]
100. test_matmul[41-41-41-7]
101. test_matmul[41-41-41-32]
102. test_matmul[41-41-64-1]
103. test_matmul[41-41-64-7]
104. test_matmul[41-41-64-32]
105. test_matmul[64-7-7-1]
106. test_matmul[64-7-7-7]
107. test_matmul[64-7-7-32]
108. test_matmul[64-7-32-1]
109. test_matmul[64-7-32-7]
110. test_matmul[64-7-32-32]
111. test_matmul[64-7-41-1]
112. test_matmul[64-7-41-7]
113. test_matmul[64-7-41-32]
114. test_matmul[64-7-64-1]
115. test_matmul[64-7-64-7]
116. est_matmul[64-7-64-32]
117. test_matmul[64-41-7-1]
118. test_matmul[64-41-7-7]
119. test_matmul[64-41-7-32]
120. test_matmul[64-41-32-1]
121. test_matmul[64-41-32-7]
122. test_matmul[64-41-32-32]
123. test_matmul[64-41-41-1]
124. test_matmul[64-41-41-7]
125. test_matmul[64-41-41-32]
126. test_matmul[64-41-64-1]
127. test_matmul[64-41-64-7]
128. test_matmul[64-41-64-32]
129. test_sqrt[7-7]
130. test_sqrt[7-32]
131. test_sqrt[7-41]
132. test_sqrt[41-7]
133. test_sqrt[41-32]
134. test_sqrt[41-41]
135. test_reciprocal[shape0]
136. test_reciprocal[shape3]
137. test_reciprocal[shape5]
138. test_reciprocal[shape6]
139. test_reciprocal[shape7]
140. test_sigmoid[shape0]
141. test_sigmoid[shape3]
142. test_sigmoid[shape5]
143. test_sigmoid[shape6]
144. test_sigmoid[shape7]
145. test_multiply[shape1]
146. test_conv2d[no_bias-activations_dtype1-weights_dtype1-1-256-256-14-14-3-3-1-1]
147. test_conv2d[no_bias-activations_dtype1-weights_dtype1-1-256-256-7-7-3-3-1-1]
148. test_conv2d[with_bias-activations_dtype1-weights_dtype1-1-256-256-14-14-3-3-1-1]
149. test_conv2d[with_bias-activations_dtype1-weights_dtype1-1-256-256-7-7-3-3-1-1]

**Comment by sdjordjevicTT** [comment]
This partial revert should fix this:
https://github.com/tenstorrent/tt-mlir/pull/789

Can you please confirm this?

**Comment by sdjordjevicTT** [comment]
@svuckovicTT can you please take a look at this one, it seems there is some problem with moving tensors from device to host...
