### ISSUE TITLE
Example case trigger issue “Assertion `device && "Device not found"' failed.”

### ISSUE THREAD

**Issue by yaoxingwei** [tenstorrent/tt-mlir#886]
### Reproduce steps：
1. Pull the latest master branch code and build.
2. Run ttmlir-translate example case:
`./build/bin/ttmlir-opt --ttir-load-system-desc --ttir-layout --convert-ttir-to-ttnn --convert-ttnn-to-emitc test/ttmlir/Dialect/TTNN/simple_multiply.mlir -o c.mlir`
3. Trigger error:
```
ttmlir-opt: /tt-mlir/lib/Dialect/TTIR/Transforms/Passes.cpp:765: virtual void mlir::tt::ttir::TTIRLayout::runOnOperation(): Assertion `device && "Device not found"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./build/bin/ttmlir-opt --ttir-load-system-desc --ttir-layout --convert-ttir-to-ttnn --convert-ttnn-to-emitc test/ttmlir/Dialect/TTNN/simple_multiply.mlir -o c.mlir
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM.so.19.0git 0x00007fc86972d1d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 69
1  libLLVM.so.19.0git 0x00007fc86972d620

```
### Root cause:
1. In commit 0c45bba:
![image](https://github.com/user-attachments/assets/d065556a-a1f9-429a-87d2-d70d55d23b5a)
 2. The function is enabled by default, but when modified to be configured via parameters, it becomes disabled by default.
 3. Many example case will run without enable the parameter: implicitDeviceOptions, so trigger the issue.

### Solution:
1. In the example case, add parameter: --ttir-implicit-device
2. Enable the parameter by default ?

Thanks

**Comment by nsmithtt** [comment]
Hi @yaoxingwei, thank you for filing an issue!

In the typical case we recommend running the full compile pipeline, which will run this pass by default:
```bash
ttmlir-opt --ttir-to-ttnn-backend-pipeline test/ttmlir/Dialect/TTNN/simple_multiply.mlir
```

Notice in the latest main the test is now defined this way.

Running individual passes is allowed, and useful for targeted tests, but the passes themselves and required ordering are subject to change.

Let us know if this resolves your issue and we can close.

**Comment by yaoxingwei** [comment]
> Hi @yaoxingwei, thank you for filing an issue!
> 
> In the typical case we recommend running the full compile pipeline, which will run this pass by default:
> 
> ```shell
> ttmlir-opt --ttir-to-ttnn-backend-pipeline test/ttmlir/Dialect/TTNN/simple_multiply.mlir
> ```
> 
> Notice in the latest main the test is now defined this way.
> 
> Running individual passes is allowed, and useful for targeted tests, but the passes themselves and required ordering are subject to change.
> 
> Let us know if this resolves your issue and we can close.

Hi @nsmithtt,

Thanks for your reply. I think this issue can be closed.
