### ISSUE TITLE
Add CCL ops to TTIR Dialect

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#923]
- ttir.all_gather
- ttir.line_all_gather
- ttir.reduce_scatter

Related issue:
- #700 

Follow this tutorial for adding a new op to the stack: https://docs.tenstorrent.com/tt-mlir/adding-an-op.html

**Comment by gfengTT** [comment]
Just noticed this.. https://github.com/tenstorrent/tt-mlir/pull/937 should resolve part of this. It adds `ttir.all_gather`.

Btw, in ttnn, `line_all_gather` has been consolidated into `all_gather` so I think we won't need it here.
