### ISSUE TITLE
Setup Belgrade Machines for Nightly Benchmark

### ISSUE THREAD

**Issue by vcanicTT** [tenstorrent/tt-mlir#930]
We should run benchmark tests as nightly jobs on Belgrade machines specified for that purpose. Those are T3000 machines, numbered from 3001 to 3008. 
Action items are:

- Check the availability of the machines
- Talk to devops team how to setup them for benchmark tests, talk about all necessary configurations thar MLIR/Optimizer team need to know
- Setup jobs for benchmark tests to run on the machines

**Comment by skhatriTT** [comment]
Hey @vcanicTT, I noticed this issue was previously closed but has been moved to In Progress on the TT-Forge project board.
Just checking in, is there any remaining work or pending task that needs to be addressed here?
