### ISSUE TITLE
stable hlo abs

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-mlir#977]
Add support for stable hlo abs, lower to ttnn and add unit tests to tt-torch and tt-xla

**Comment by mmanzoorTT** [comment]
PR for tt-mlir implementation https://github.com/tenstorrent/tt-mlir/pull/670
PR for tt-xla test https://github.com/tenstorrent/tt-xla/pull/15/

**Comment by mmanzoorTT** [comment]
tt-torch unit test is pending

**Comment by mmanzoorTT** [comment]
tt-torch tests added https://github.com/tenstorrent/tt-torch/pull/8
