### ISSUE TITLE
stable hlo compare

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-mlir#986]
Lower all compare ops to ttnn and add unit tests for each to tt-torch and tt-xla.

**Comment by mmanzoorTT** [comment]
end-to-end implementation of compare ops (EQ, NE, GE, GT, LE, LT): https://github.com/tenstorrent/tt-mlir/pull/821
stableHLO conversion: https://github.com/tenstorrent/tt-mlir/pull/837

**Comment by mmanzoorTT** [comment]
unit tests pending

**Comment by mmanzoorTT** [comment]
tt-torch unit tests https://github.com/tenstorrent/tt-torch/pull/43
tt-xla unit tests https://github.com/tenstorrent/tt-xla/pull/92
