### ISSUE TITLE
missing ttnn.cos op support

### ISSUE THREAD

**Issue by mstojkovicTT** [tenstorrent/tt-mlir#987]

**Comment by sdjordjevicTT** [comment]
@nvukobratTT Is this something new? How urgent do we need to pick this up?

**Comment by nvukobratTT** [comment]
> @nvukobratTT Is this something new? How urgent do we need to pick this up?

We missed this op as it was hidden behind other Metal issues.. So it has same priorities as other Llama 3B related issues ops requirements :))

**Comment by sdjordjevicTT** [comment]
Thanks for clarifying, someone will pick this up as soon as possible. :)

**Comment by sdjordjevicTT** [comment]
This op is now supported in TT-MLIR.
